// Regenerates inst/htmlwidgets/lib/mosaic-bundle.min.js: the mosaic JS
// runtime (mosaic-spec + mosaic-core + duckdb-wasm's own JS API --
// *not* duckdb-wasm's multi-megabyte .wasm engine binary, which stays a
// separate, optionally-cached asset -- see R/duckdb_cache.R) bundled and
// minified into one local file, so vgplotr no longer needs a CDN
// (esm.sh) to load the library code itself at view time.
//
// Run from this directory:
//   cd data-raw/js && npm install && node build.js
//
// MOSAIC_VERSION/DUCKDB_WASM_VERSION here must match package.json's
// pinned dependency versions, and DUCKDB_WASM_VERSION must also match
// the constant of the same name in inst/htmlwidgets/vgplotr.js (which
// uses it to fetch/validate the separately-cached engine binary).
//
// format: "iife", not "esm" -- deliberately: a <script type="module">
// always fetches its src in CORS mode per the HTML spec, and a page
// opened via file:// can never satisfy that (Chrome blocks it outright;
// Firefox's strict per-file file:// origin policy blocks it too, even
// for a script sitting right next to the HTML) -- confirmed directly,
// this broke a real user's file:// widget with "CORS request not http"/
// "Module source URI is not allowed". A classic (non-module) script
// isn't subject to either restriction. entry.js's own `import` statements
// are still fine as *source* -- esbuild resolves/inlines them at bundle
// time regardless of the output format; only the *output*'s module-ness
// changes. inst/htmlwidgets/vgplotr.yaml must NOT declare `type: module`
// for this script, to match.
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const MOSAIC_VERSION = "0.31.0";
const DUCKDB_WASM_VERSION = "1.29.0";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../../inst/htmlwidgets/lib/mosaic-bundle.min.js");

const result = await build({
  entryPoints: [resolve(__dirname, "entry.js")],
  bundle: true,
  minify: true,
  format: "iife",
  outfile: OUT,
  metafile: true,
  banner: {
    js:
      `// Generated by data-raw/js/build.js -- DO NOT EDIT BY HAND.\n` +
      `// Bundles @uwdata/mosaic-spec@${MOSAIC_VERSION}, @uwdata/mosaic-core@${MOSAIC_VERSION},\n` +
      `// and @duckdb/duckdb-wasm@${DUCKDB_WASM_VERSION}'s JS API (not its .wasm binary).`,
  },
});

const bytes = (await import("node:fs")).statSync(OUT).size;
console.log(`Wrote ${OUT} (${(bytes / 1024).toFixed(0)} KB)`);
