# Regenerates R/marks-generated.R, R/interactors-generated.R, and
# R/attrs-generated.R from mosaic's own published JSON schema -- the same
# source of truth uwdata/mosaic's own bin/generate-python-api.js uses to
# generate the Python API's marks/attributes.
#
# Run interactively (source this file, or `Rscript data-raw/update-schema.R`)
# whenever MOSAIC_VERSION here is bumped (keep it in sync with the version
# pinned in inst/htmlwidgets/vgplotr.js, so the functions this generates
# match what the runtime the browser actually loads supports) or whenever
# vgplotr seems to be missing a mark/interactor/attribute mosaic supports.
#
# What this does NOT cover (hand-written, not schema-driven): transforms
# (R/transforms.R -- a different schema file, Transform.ts, without a
# corresponding section in the JSON schema's mark/attribute defs), legends
# (only 3 types, small enough to maintain by hand in R/legend.R), and
# data-source options (R/create.R).

MOSAIC_VERSION <- "0.31.0"

schema_url <- sprintf(
  "https://cdn.jsdelivr.net/npm/@uwdata/mosaic-spec@%s/dist/mosaic-schema.json",
  MOSAIC_VERSION
)
schema <- jsonlite::fromJSON(schema_url, simplifyVector = FALSE)
defs <- schema$definitions

camel_to_snake <- function(name) {
  tolower(gsub("([a-z0-9])([A-Z])", "\\1_\\2", name))
}

ref_name <- function(ref) sub("^#/definitions/", "", ref$`$ref`)

# A mark definition either has `properties.mark.const` directly, or is a
# union (`anyOf`/`allOf`) whose branches all agree on the same
# `properties.mark.const` (e.g. densityX/densityY) -- mirrors mosaic's own
# markInfo() in bin/generate-python-api.js.
mark_const <- function(def) {
  direct <- def$properties$mark$const
  if (!is.null(direct)) return(direct)
  branches <- if (!is.null(def$anyOf)) def$anyOf else def$allOf
  consts <- unique(unlist(lapply(branches, function(b) b$properties$mark$const)))
  if (length(consts) == 1) consts else NULL
}

marks <- sort(unique(unlist(lapply(defs, mark_const))))

interactor_types <- vapply(
  schema$definitions$PlotInteractor$anyOf,
  function(r) defs[[ref_name(r)]]$properties$select$const,
  character(1)
)

input_types <- vapply(
  c("Menu", "Search", "Slider", "Table"),
  function(nm) defs[[nm]]$properties$input$const,
  character(1)
)

plot_attrs <- sort(names(defs$PlotAttributes$properties))

cat(length(marks), "marks,", length(interactor_types), "interactors,",
    length(input_types), "inputs,", length(plot_attrs), "plot attributes\n")

# --- R/marks-generated.R -----------------------------------------------

mark_lines <- c(
  "# Generated by data-raw/update-schema.R from mosaic's JSON schema.",
  "# DO NOT EDIT BY HAND -- rerun that script instead.",
  "#",
  "# One vg_<mark>() wrapper per mark type in the mosaic-spec schema -- e.g.",
  "# vg_dot(spec, x = ~a, y = ~b) is exactly vg_mark(spec, \"dot\", x = ~a, y",
  "# = ~b). All share vg_mark()'s documentation (R/mark.R) via @rdname.",
  ""
)
for (m in marks) {
  fn <- paste0("vg_", camel_to_snake(m))
  mark_lines <- c(
    mark_lines,
    "#' @rdname vg_mark",
    "#' @export",
    sprintf('%s <- function(spec = NULL, ...) vg_mark(spec, "%s", ...)', fn, m),
    ""
  )
}
writeLines(mark_lines, "R/marks-generated.R")

# --- R/interactors-generated.R ------------------------------------------

inter_lines <- c(
  "# Generated by data-raw/update-schema.R from mosaic's JSON schema.",
  "# DO NOT EDIT BY HAND -- rerun that script instead.",
  "",
  "# Which vg_interactor()/vg_input() types are embedded inside a plot's",
  "# mark list vs. which live in the surrounding layout as standalone",
  "# widgets -- see vg_interactor_placement() in R/interactor.R.",
  ".vg_interactor_types <- c(",
  paste0('  "', interactor_types, '"', collapse = ",\n"),
  ")",
  "",
  ".vg_input_types <- c(",
  paste0('  "', input_types, '"', collapse = ",\n"),
  ")",
  "",
  "# One vg_<type>() wrapper per interactor type (embedded in a plot, e.g.",
  "# vg_pan_zoom()) and input type (a standalone layout widget, e.g.",
  "# vg_menu()) in the mosaic-spec schema -- e.g. vg_toggle(spec, as =",
  "# param(sel)) is exactly vg_interactor(spec, \"toggle\", as = param(sel)).",
  "# All share vg_interactor()'s documentation (R/interactor.R) via @rdname.",
  ""
)
for (type in c(interactor_types, input_types)) {
  fn <- paste0("vg_", camel_to_snake(type))
  args <- if (type %in% input_types) "..." else "spec = NULL, ..."
  call_args <- if (type %in% input_types) "NULL, " else "spec, "
  inter_lines <- c(
    inter_lines,
    "#' @rdname vg_interactor",
    "#' @export",
    sprintf('%s <- function(%s) vg_interactor(%s"%s", ...)', fn, args, call_args, type),
    ""
  )
}
writeLines(inter_lines, "R/interactors-generated.R")

# --- R/attrs-generated.R -------------------------------------------------

attr_lines <- c(
  "# Generated by data-raw/update-schema.R from mosaic's JSON schema.",
  "# DO NOT EDIT BY HAND -- rerun that script instead.",
  "",
  "# All plot-level attribute names (mosaic-spec's PlotAttributes), used by",
  "# split_plot_args() in R/utils.R to tell a plot-level attribute (width,",
  "# xDomain, colorScheme, ...) apart from a mark/interactor's own",
  "# encodings/options when both arrive together via one `...`.",
  ".vg_plot_attrs <- c(",
  paste0('  "', plot_attrs, '"', collapse = ",\n"),
  ")"
)
writeLines(attr_lines, "R/attrs-generated.R")

cat("Wrote R/marks-generated.R, R/interactors-generated.R, R/attrs-generated.R\n")
