# Generated by data-raw/update-schema.R from mosaic's JSON schema.
# DO NOT EDIT BY HAND -- rerun that script instead.
#
# One vg_guide_*() constructor per axis-guide channel/family in
# mosaic-spec's PlotAttributes -- see data-raw/update-schema.R's own
# comments for how properties are classified into these.

#' @include utils.R
NULL

#' Set axis-guide properties for a position scale (x or y)
#'
#' `vg_guide_x()`/`vg_guide_y()` set the axis-guide properties
#' mosaic-spec exposes per positional axis (`xAxis`, `xTicks`, ... --
#' substitute `y` for the vertical axis). Like the `xScale`/`yScale`
#' properties handled by [vg_scale_position()], these are already
#' plot-level attributes that [vg_plot()]/[vg_attributes()] accept
#' directly, snake_case (e.g., `x_ticks =`).
#'
#' These are named `vg_guide_*()` rather than `vg_axis_*()` to avoid
#' colliding with `vg_mark_axis_x()`/`vg_mark_axis_y()`
#' (mosaic-spec's `axisX`/`axisY` *mark*, a drawable,
#' independently-styled axis) -- a different (if related) thing from
#' the plain `xAxis`/`yAxis` guide attributes set here, which appear
#' automatically alongside a plot's marks. Same story for the
#' analogous facet guides, [vg_guide_facet()] (vs.
#' `vg_mark_axis_fx()`/`vg_mark_axis_fy()`, mosaic's `axisFx`/`axisFy`
#' marks).
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param which Which axis this sets: `"x"` or `"y"`.
#' @param position The side of the frame on which to place the implicit axis: *top* or *bottom* for *x*. (`xAxis`/`yAxis`).
#' @param ticks The desired approximate number of axis ticks, or an explicit array of tick values, or an interval such as *day* or *month*. (`xTicks`/`yTicks`).
#' @param tick_spacing The desired approximate spacing between adjacent axis ticks, affecting the default **ticks**; defaults to 80 pixels for *x* and *fx*, and 35 pixels for *y* and *fy*. (`xTickSpacing`/`yTickSpacing`).
#' @param tick_size The length of axis tick marks in pixels; negative values extend in the opposite direction. (`xTickSize`/`yTickSize`).
#' @param tick_padding The distance between an axis tick mark and its associated text label (in pixels); often defaults to 3, but may be affected by **xTickSize** and **xTickRotate**. (`xTickPadding`/`yTickPadding`).
#' @param tick_format How to format inputs (abstract values) for axis tick labels; one of: - a d3-format string for numeric scales - a d3-time-format string for temporal scales : https://d3js.org/d3-time : https://d3js.org/d3-time-format (`xTickFormat`/`yTickFormat`).
#' @param tick_rotate The rotation angle of axis tick labels in degrees clocksize; defaults to 0. (`xTickRotate`/`yTickRotate`).
#' @param grid Whether to show a grid aligned with the scale’s ticks. (`xGrid`/`yGrid`).
#' @param line If true, draw a line along the axis; if false (default), do not. (`xLine`/`yLine`).
#' @param label A textual label to show on the axis or legend; if null, show no label. (`xLabel`/`yLabel`).
#' @param label_anchor Where to place the axis **label** relative to the plot’s frame. (`xLabelAnchor`/`yLabelAnchor`).
#' @param label_offset The axis **label** position offset (in pixels); default depends on margins and orientation. (`xLabelOffset`/`yLabelOffset`).
#' @param label_arrow Whether to apply a directional arrow such as → or ↑ to the x-axis scale label. (`xLabelArrow`/`yLabelArrow`).
#' @param font_variant The font-variant attribute for axis ticks; defaults to *tabular-nums* for quantitative axes. (`xFontVariant`/`yFontVariant`).
#' @param aria_label A short label representing the axis in the accessibility tree. (`xAriaLabel`/`yAriaLabel`).
#' @param aria_description A textual description for the axis in the accessibility tree. (`xAriaDescription`/`yAriaDescription`).
#' @param ... Additional plot-level attributes not covered above, snake_case
#'   (e.g., `x_domain =`) -- translated to mosaic's own camelCase key.
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b) |>
#'   vg_guide_x(label = "A", grid = TRUE) |>
#'   vg_guide_y(label = "B", tick_format = ".0f")
vg_guide_position <- function(spec = NULL, which = c("x", "y"), position = vg_unset, ticks = vg_unset, tick_spacing = vg_unset, tick_size = vg_unset, tick_padding = vg_unset, tick_format = vg_unset, tick_rotate = vg_unset, grid = vg_unset, line = vg_unset, label = vg_unset, label_anchor = vg_unset, label_offset = vg_unset, label_arrow = vg_unset, font_variant = vg_unset, aria_label = vg_unset, aria_description = vg_unset, ...) {
  which <- match.arg(which)
  context <- paste0("vg_guide_", which, "()")
  suffixes <- c(position = "Axis", ticks = "Ticks", tick_spacing = "TickSpacing", tick_size = "TickSize", tick_padding = "TickPadding", tick_format = "TickFormat", tick_rotate = "TickRotate", grid = "Grid", line = "Line", label = "Label", label_anchor = "LabelAnchor", label_offset = "LabelOffset", label_arrow = "LabelArrow", font_variant = "FontVariant", aria_label = "AriaLabel", aria_description = "AriaDescription")
  attrs <- prefixed_attrs(which, suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_guide_position
#' @export
vg_guide_x <- wrapper_function(vg_guide_position, which = "x")

#' @rdname vg_guide_position
#' @export
vg_guide_y <- wrapper_function(vg_guide_position, which = "y")

#' Set axis-guide properties for a facet scale (fx or fy)
#'
#' `vg_guide_fx()`/`vg_guide_fy()` set the axis-guide properties
#' mosaic-spec exposes per facet axis (`fxAxis`, `fxTicks`, ... --
#' substitute `fy` for the row facet axis). This is the facet
#' counterpart of [vg_guide_position()]; the property set (which lacks
#' `label_arrow`, among others) is derived from the schema, not
#' hand-picked.
#'
#' See [vg_guide_position()] for why these are `vg_guide_*()` rather
#' than `vg_axis_*()` (to avoid colliding with `vg_mark_axis_fx()`/
#' `vg_mark_axis_fy()`, mosaic's `axisFx`/`axisFy` marks).
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param which Which facet axis this sets: `"fx"` or `"fy"`.
#' @param position The side of the frame on which to place the implicit axis: *top* or *bottom* for *fx*. (`fxAxis`/`fyAxis`).
#' @param ticks The desired approximate number of axis ticks, or an explicit array of tick values, or an interval such as *day* or *month*. (`fxTicks`/`fyTicks`).
#' @param tick_spacing The desired approximate spacing between adjacent axis ticks, affecting the default **ticks**; defaults to 80 pixels for *x* and *fx*, and 35 pixels for *y* and *fy*. (`fxTickSpacing`/`fyTickSpacing`).
#' @param tick_size The length of axis tick marks in pixels; negative values extend in the opposite direction. (`fxTickSize`/`fyTickSize`).
#' @param tick_padding The distance between an axis tick mark and its associated text label (in pixels); often defaults to 3, but may be affected by **fxTickSize** and **fxTickRotate**. (`fxTickPadding`/`fyTickPadding`).
#' @param tick_format How to format inputs (abstract values) for axis tick labels; one of: - a d3-format string for numeric scales - a d3-time-format string for temporal scales : https://d3js.org/d3-time : https://d3js.org/d3-time-format (`fxTickFormat`/`fyTickFormat`).
#' @param tick_rotate The rotation angle of axis tick labels in degrees clocksize; defaults to 0. (`fxTickRotate`/`fyTickRotate`).
#' @param grid Whether to show a grid aligned with the scale’s ticks. (`fxGrid`/`fyGrid`).
#' @param line If true, draw a line along the axis; if false (default), do not. (`fxLine`/`fyLine`).
#' @param label A textual label to show on the axis or legend; if null, show no label. (`fxLabel`/`fyLabel`).
#' @param label_anchor Where to place the axis **label** relative to the plot’s frame. (`fxLabelAnchor`/`fyLabelAnchor`).
#' @param label_offset The axis **label** position offset (in pixels); default depends on margins and orientation. (`fxLabelOffset`/`fyLabelOffset`).
#' @param font_variant The font-variant attribute for axis ticks; defaults to *tabular-nums* for quantitative axes. (`fxFontVariant`/`fyFontVariant`).
#' @param aria_label A short label representing the axis in the accessibility tree. (`fxAriaLabel`/`fyAriaLabel`).
#' @param aria_description A textual description for the axis in the accessibility tree. (`fxAriaDescription`/`fyAriaDescription`).
#' @param ... Additional plot-level attributes not covered above, snake_case
#'   (e.g., `x_domain =`) -- translated to mosaic's own camelCase key.
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, fx = ~g) |>
#'   vg_guide_fx(label = "Group")
vg_guide_facet <- function(spec = NULL, which = c("fx", "fy"), position = vg_unset, ticks = vg_unset, tick_spacing = vg_unset, tick_size = vg_unset, tick_padding = vg_unset, tick_format = vg_unset, tick_rotate = vg_unset, grid = vg_unset, line = vg_unset, label = vg_unset, label_anchor = vg_unset, label_offset = vg_unset, font_variant = vg_unset, aria_label = vg_unset, aria_description = vg_unset, ...) {
  which <- match.arg(which)
  context <- paste0("vg_guide_", which, "()")
  suffixes <- c(position = "Axis", ticks = "Ticks", tick_spacing = "TickSpacing", tick_size = "TickSize", tick_padding = "TickPadding", tick_format = "TickFormat", tick_rotate = "TickRotate", grid = "Grid", line = "Line", label = "Label", label_anchor = "LabelAnchor", label_offset = "LabelOffset", font_variant = "FontVariant", aria_label = "AriaLabel", aria_description = "AriaDescription")
  attrs <- prefixed_attrs(which, suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_guide_facet
#' @export
vg_guide_fx <- wrapper_function(vg_guide_facet, which = "fx")

#' @rdname vg_guide_facet
#' @export
vg_guide_fy <- wrapper_function(vg_guide_facet, which = "fy")

#' Set axis-guide properties for the color scale
#'
#' `vg_guide_color()` sets the axis-guide properties mosaic-spec
#' exposes for the `color` channel (`colorLabel`, `colorTickFormat`) --
#' the counterpart of [vg_scale_color()] for the color channel's
#' label/tick formatting rather than its domain/range/palette.
#'
#' This is named `vg_guide_color()` rather than `vg_legend_color()`
#' because `vg_legend_color()` already exists and means something
#' different: it adds an actual rendered color legend (a
#' standalone/embedded legend mark, [vg_legend()]) to the spec.
#' `vg_guide_color()` only sets these plot attributes -- it neither
#' shows nor requires a legend to be present.
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param tick_format How to format inputs (abstract values) for axis tick labels; one of: - a d3-format string for numeric scales - a d3-time-format string for temporal scales : https://d3js.org/d3-time : https://d3js.org/d3-time-format (`colorTickFormat`).
#' @param label A textual label to show on the axis or legend; if null, show no label. (`colorLabel`).
#' @param ... Additional plot-level attributes not covered above, snake_case
#'   (e.g., `x_domain =`) -- translated to mosaic's own camelCase key.
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, fill = ~g) |>
#'   vg_guide_color(label = "Group")
vg_guide_color <- function(spec = NULL, tick_format = vg_unset, label = vg_unset, ...) {
  context <- "vg_guide_color()"
  suffixes <- c(tick_format = "TickFormat", label = "Label")
  attrs <- prefixed_attrs("color", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set axis-guide properties for the opacity scale
#'
#' `vg_guide_opacity()` sets the axis-guide properties mosaic-spec
#' exposes for the `opacity` channel -- the counterpart of
#' [vg_scale_opacity()] for the opacity channel's label/tick
#' formatting rather than its domain/range.
#'
#' See [vg_guide_color()] for why this is `vg_guide_opacity()` rather
#' than `vg_legend_opacity()` (already taken by [vg_legend()]'s actual
#' rendered legend).
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param tick_format How to format inputs (abstract values) for axis tick labels; one of: - a d3-format string for numeric scales - a d3-time-format string for temporal scales : https://d3js.org/d3-time : https://d3js.org/d3-time-format (`opacityTickFormat`).
#' @param label A textual label to show on the axis or legend; if null, show no label. (`opacityLabel`).
#' @param ... Additional plot-level attributes not covered above, snake_case
#'   (e.g., `x_domain =`) -- translated to mosaic's own camelCase key.
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, opacity = ~g) |>
#'   vg_guide_opacity(label = "Group")
vg_guide_opacity <- function(spec = NULL, tick_format = vg_unset, label = vg_unset, ...) {
  context <- "vg_guide_opacity()"
  suffixes <- c(tick_format = "TickFormat", label = "Label")
  attrs <- prefixed_attrs("opacity", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set the axis-guide property for the radius scale
#'
#' `vg_guide_r()` (aliased as `vg_guide_radius()`) sets the axis-guide
#' propert(y/ies) mosaic-spec exposes for the `r` channel -- the
#' counterpart of [vg_scale_r()]/[vg_scale_radius()] for the radius
#' channel's label rather than its domain/range. Which properties
#' exist here (just a label, no tick-format) is derived from the
#' schema, not hand-picked.
#'
#' See [vg_guide_color()] for why this is `vg_guide_r()`/
#' `vg_guide_radius()` rather than `vg_legend_r()`/`vg_legend_radius()`
#' -- mosaic doesn't have a dedicated `r`-typed legend mark to collide
#' with here (radius/size is usually shown via [vg_legend_symbol()]
#' instead), but the naming stays consistent with [vg_guide_color()]/
#' [vg_guide_opacity()].
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param label A textual label to show on the axis or legend; if null, show no label. (`rLabel`).
#' @param ... Additional plot-level attributes not covered above, snake_case
#'   (e.g., `x_domain =`) -- translated to mosaic's own camelCase key.
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, r = ~g) |>
#'   vg_guide_r(label = "Size")
vg_guide_r <- function(spec = NULL, label = vg_unset, ...) {
  context <- "vg_guide_r()"
  suffixes <- c(label = "Label")
  attrs <- prefixed_attrs("r", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_guide_r
#' @export
vg_guide_radius <- vg_guide_r

#' Set global default axis-guide properties (all position axes)
#'
#' `vg_guide_all()` sets mosaic-spec's plot-wide fallback defaults for
#' the axis-guide properties -- unlike `xAxis`/`xGrid`/etc. (set via
#' [vg_guide_position()]) or `fxAxis`/etc. (via [vg_guide_facet()]),
#' which only affect one axis, these bare attributes are mosaic's own
#' defaults applied to *every* position axis (`x`, `y`, `fx`, `fy`)
#' that doesn't set its own value. For the analogous scale defaults,
#' see [vg_scale_all()].
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param position The side of the frame on which to place the implicit axis: *top* or *bottom* for *x* or *fx*, or *left* or *right* for *y* or *fy*. (`axis`).
#' @param grid Whether to show a grid aligned with the scale’s ticks. (`grid`).
#' @param aria_label The aria-label attribute on the SVG root. (`ariaLabel`).
#' @param aria_description The aria-description attribute on the SVG root. (`ariaDescription`).
#' @param ... Additional plot-level attributes not covered above, snake_case
#'   (e.g., `x_domain =`) -- translated to mosaic's own camelCase key.
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b) |>
#'   vg_guide_all(grid = TRUE)
vg_guide_all <- function(spec = NULL, position = vg_unset, grid = vg_unset, aria_label = vg_unset, aria_description = vg_unset, ...) {
  context <- "vg_guide_all()"
  suffixes <- c(position = "axis", grid = "grid", aria_label = "ariaLabel", aria_description = "ariaDescription")
  attrs <- prefixed_attrs("", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

