# Generated by data-raw/update-schema.R from mosaic's JSON schema.
# DO NOT EDIT BY HAND -- rerun that script instead.
#
# One vg_guide_*() constructor per axis-guide channel/family in
# mosaic-spec's PlotAttributes -- see data-raw/update-schema.R's own
# comments for how properties are classified into these.

#' @include utils.R
NULL

#' Set axis-guide properties for a position scale (x or y)
#'
#' `vg_guide_x()` and `vg_guide_y()` set the properties of a plot's x and y
#' axes: labels, ticks, grid lines, and so on (Mosaic's `xAxis`, `xTicks`,
#' ... attributes, and the same for `y`). The same attributes can also be
#' given to [vg_plot()] or [vg_attributes()], as `x_ticks =` and so on.
#' `vg_guide_position()` is the general form, taking `which`.
#'
#' These set the axes drawn automatically with a plot's marks. To add an axis
#' as a mark of its own, styled separately, see [vg_mark_axis_x()]. For the
#' facet axes, see [vg_guide_facet()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param which Which axis this sets: `"x"` or `"y"`.
#' @param position `<"top" | "bottom" | "both" | boolean | NULL | param()>` The side of the frame on which to place the implicit axis: *top* or *bottom* for *x*. (`xAxis`/`yAxis`).
#' @param ticks `<number | "day"/"week"/"month"/... | vector | param()>` The desired approximate number of axis ticks, or an explicit array of tick values, or an interval such as *day* or *month*. (`xTicks`/`yTicks`).
#' @param tick_spacing `<number | param()>` The desired approximate spacing between adjacent axis ticks, affecting the default **ticks**; defaults to 80 pixels for *x* and *fx*, and 35 pixels for *y* and *fy*. (`xTickSpacing`/`yTickSpacing`).
#' @param tick_size `<number | param()>` The length of axis tick marks in pixels; negative values extend in the opposite direction. (`xTickSize`/`yTickSize`).
#' @param tick_padding `<number | param()>` The distance between an axis tick mark and its associated text label (in pixels); often defaults to 3, but may be affected by **xTickSize** and **xTickRotate**. (`xTickPadding`/`yTickPadding`).
#' @param tick_format `<string | NULL | param()>` How to format inputs (abstract values) for axis tick labels; one of: - a d3-format string for numeric scales - a d3-time-format string for temporal scales : https://d3js.org/d3-time : https://d3js.org/d3-time-format (`xTickFormat`/`yTickFormat`).
#' @param tick_rotate `<number | param()>` The rotation angle of axis tick labels in degrees clocksize; defaults to 0. (`xTickRotate`/`yTickRotate`).
#' @param grid `<boolean | string | "day"/"week"/"month"/... | number | vector | param()>` Whether to show a grid aligned with the scale’s ticks. (`xGrid`/`yGrid`).
#' @param line `<boolean | param()>` If true, draw a line along the axis; if false (default), do not. (`xLine`/`yLine`).
#' @param label `<string | NULL | param()>` A textual label to show on the axis or legend; if null, show no label. (`xLabel`/`yLabel`).
#' @param label_anchor `<"top" | "right" | "bottom" | "left" | "center" | param()>` Where to place the axis **label** relative to the plot’s frame. (`xLabelAnchor`/`yLabelAnchor`).
#' @param label_offset `<number | param()>` The axis **label** position offset (in pixels); default depends on margins and orientation. (`xLabelOffset`/`yLabelOffset`).
#' @param label_arrow `<"auto" | "up" | "right" | "down" | "left" | "none" | TRUE | FALSE | NULL | param()>` Whether to apply a directional arrow such as → or ↑ to the x-axis scale label. (`xLabelArrow`/`yLabelArrow`).
#' @param font_variant `<string | param()>` The font-variant attribute for axis ticks; defaults to *tabular-nums* for quantitative axes. (`xFontVariant`/`yFontVariant`).
#' @param aria_label `<string | param()>` A short label representing the axis in the accessibility tree. (`xAriaLabel`/`yAriaLabel`).
#' @param aria_description `<string | param()>` A textual description for the axis in the accessibility tree. (`xAriaDescription`/`yAriaDescription`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b) |>
#'   vg_guide_x(label = "A", grid = TRUE) |>
#'   vg_guide_y(label = "B", tick_format = ".0f")
vg_guide_position <- function(spec = NULL, which = c("x", "y"), position = vg_unset, ticks = vg_unset, tick_spacing = vg_unset, tick_size = vg_unset, tick_padding = vg_unset, tick_format = vg_unset, tick_rotate = vg_unset, grid = vg_unset, line = vg_unset, label = vg_unset, label_anchor = vg_unset, label_offset = vg_unset, label_arrow = vg_unset, font_variant = vg_unset, aria_label = vg_unset, aria_description = vg_unset, ...) {
  which <- match.arg(which)
  context <- paste0("vg_guide_", which, "()")
  suffixes <- c(position = "Axis", ticks = "Ticks", tick_spacing = "TickSpacing", tick_size = "TickSize", tick_padding = "TickPadding", tick_format = "TickFormat", tick_rotate = "TickRotate", grid = "Grid", line = "Line", label = "Label", label_anchor = "LabelAnchor", label_offset = "LabelOffset", label_arrow = "LabelArrow", font_variant = "FontVariant", aria_label = "AriaLabel", aria_description = "AriaDescription")
  attrs <- prefixed_attrs(which, suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_guide_position
#' @export
vg_guide_x <- wrapper_function(vg_guide_position, which = "x")

#' @rdname vg_guide_position
#' @export
vg_guide_y <- wrapper_function(vg_guide_position, which = "y")

#' Set axis-guide properties for a facet scale (fx or fy)
#'
#' `vg_guide_fx()` and `vg_guide_fy()` set the properties of a plot's facet
#' axes (`fxAxis`, `fxTicks`, ..., and the same for `fy`) -- the facet
#' counterpart of [vg_guide_position()], with a few fewer properties (no
#' `label_arrow`, for example). To add a facet axis as a mark of its own,
#' see [vg_mark_axis_fx()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param which Which facet axis this sets: `"fx"` or `"fy"`.
#' @param position `<"top" | "bottom" | "both" | boolean | NULL | param()>` The side of the frame on which to place the implicit axis: *top* or *bottom* for *fx*. (`fxAxis`/`fyAxis`).
#' @param ticks `<number | "day"/"week"/"month"/... | vector | param()>` The desired approximate number of axis ticks, or an explicit array of tick values, or an interval such as *day* or *month*. (`fxTicks`/`fyTicks`).
#' @param tick_spacing `<number | param()>` The desired approximate spacing between adjacent axis ticks, affecting the default **ticks**; defaults to 80 pixels for *x* and *fx*, and 35 pixels for *y* and *fy*. (`fxTickSpacing`/`fyTickSpacing`).
#' @param tick_size `<number | param()>` The length of axis tick marks in pixels; negative values extend in the opposite direction. (`fxTickSize`/`fyTickSize`).
#' @param tick_padding `<number | param()>` The distance between an axis tick mark and its associated text label (in pixels); often defaults to 3, but may be affected by **fxTickSize** and **fxTickRotate**. (`fxTickPadding`/`fyTickPadding`).
#' @param tick_format `<string | NULL | param()>` How to format inputs (abstract values) for axis tick labels; one of: - a d3-format string for numeric scales - a d3-time-format string for temporal scales : https://d3js.org/d3-time : https://d3js.org/d3-time-format (`fxTickFormat`/`fyTickFormat`).
#' @param tick_rotate `<number | param()>` The rotation angle of axis tick labels in degrees clocksize; defaults to 0. (`fxTickRotate`/`fyTickRotate`).
#' @param grid `<boolean | string | "day"/"week"/"month"/... | number | vector | param()>` Whether to show a grid aligned with the scale’s ticks. (`fxGrid`/`fyGrid`).
#' @param line `<boolean | param()>` If true, draw a line along the axis; if false (default), do not. (`fxLine`/`fyLine`).
#' @param label `<string | NULL | param()>` A textual label to show on the axis or legend; if null, show no label. (`fxLabel`/`fyLabel`).
#' @param label_anchor `<"top" | "right" | "bottom" | "left" | "center" | param()>` Where to place the axis **label** relative to the plot’s frame. (`fxLabelAnchor`/`fyLabelAnchor`).
#' @param label_offset `<number | param()>` The axis **label** position offset (in pixels); default depends on margins and orientation. (`fxLabelOffset`/`fyLabelOffset`).
#' @param font_variant `<string | param()>` The font-variant attribute for axis ticks; defaults to *tabular-nums* for quantitative axes. (`fxFontVariant`/`fyFontVariant`).
#' @param aria_label `<string | param()>` A short label representing the axis in the accessibility tree. (`fxAriaLabel`/`fyAriaLabel`).
#' @param aria_description `<string | param()>` A textual description for the axis in the accessibility tree. (`fxAriaDescription`/`fyAriaDescription`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, fx = ~g) |>
#'   vg_guide_fx(label = "Group")
vg_guide_facet <- function(spec = NULL, which = c("fx", "fy"), position = vg_unset, ticks = vg_unset, tick_spacing = vg_unset, tick_size = vg_unset, tick_padding = vg_unset, tick_format = vg_unset, tick_rotate = vg_unset, grid = vg_unset, line = vg_unset, label = vg_unset, label_anchor = vg_unset, label_offset = vg_unset, font_variant = vg_unset, aria_label = vg_unset, aria_description = vg_unset, ...) {
  which <- match.arg(which)
  context <- paste0("vg_guide_", which, "()")
  suffixes <- c(position = "Axis", ticks = "Ticks", tick_spacing = "TickSpacing", tick_size = "TickSize", tick_padding = "TickPadding", tick_format = "TickFormat", tick_rotate = "TickRotate", grid = "Grid", line = "Line", label = "Label", label_anchor = "LabelAnchor", label_offset = "LabelOffset", font_variant = "FontVariant", aria_label = "AriaLabel", aria_description = "AriaDescription")
  attrs <- prefixed_attrs(which, suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_guide_facet
#' @export
vg_guide_fx <- wrapper_function(vg_guide_facet, which = "fx")

#' @rdname vg_guide_facet
#' @export
vg_guide_fy <- wrapper_function(vg_guide_facet, which = "fy")

#' Set axis-guide properties for the color and opacity scales
#'
#' `vg_guide_color()` and `vg_guide_opacity()` set the axis-guide properties of the `color` and `opacity` channels. They take the same arguments; each is described below.
#'
#' `vg_guide_color()` sets the label and tick format of the color scale
#' (`colorLabel`, `colorTickFormat`) -- the counterpart of [vg_scale_color()],
#' which sets the scale's domain, range and colors. It doesn't add a legend;
#' for that, see [vg_legend_color()].
#'
#' `vg_guide_opacity()` does the same for the opacity scale, the counterpart
#' of [vg_scale_opacity()]. It doesn't add a legend; for that, see
#' [vg_legend_opacity()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param tick_format `<string | NULL | param()>` How to format inputs (abstract values) for axis tick labels; one of: - a d3-format string for numeric scales - a d3-time-format string for temporal scales : https://d3js.org/d3-time : https://d3js.org/d3-time-format (`colorTickFormat`/`opacityTickFormat`).
#' @param label `<string | NULL | param()>` A textual label to show on the axis or legend; if null, show no label. (`colorLabel`/`opacityLabel`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family guide functions
#' @rdname vg_guide_color
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, fill = ~g) |>
#'   vg_guide_color(label = "Group")
#' vg_mark_dot(x = ~a, y = ~b, opacity = ~g) |>
#'   vg_guide_opacity(label = "Group")
vg_guide_color <- function(spec = NULL, tick_format = vg_unset, label = vg_unset, ...) {
  context <- "vg_guide_color()"
  suffixes <- c(tick_format = "TickFormat", label = "Label")
  attrs <- prefixed_attrs("color", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_guide_color
#' @export
vg_guide_opacity <- function(spec = NULL, tick_format = vg_unset, label = vg_unset, ...) {
  context <- "vg_guide_opacity()"
  suffixes <- c(tick_format = "TickFormat", label = "Label")
  attrs <- prefixed_attrs("opacity", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set the axis-guide property for the radius scale
#'
#' `vg_guide_r()` (also called `vg_guide_radius()`) sets the label of the
#' radius scale -- the counterpart of [vg_scale_r()]. A legend for sizes can
#' be made with [vg_legend_symbol()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param label `<string | NULL | param()>` A textual label to show on the axis or legend; if null, show no label. (`rLabel`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, r = ~g) |>
#'   vg_guide_r(label = "Size")
vg_guide_r <- function(spec = NULL, label = vg_unset, ...) {
  context <- "vg_guide_r()"
  suffixes <- c(label = "Label")
  attrs <- prefixed_attrs("r", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_guide_r
#' @export
vg_guide_radius <- vg_guide_r

#' Set global default axis-guide properties (all position axes)
#'
#' `vg_guide_all()` sets defaults for all of a plot's position axes (`x`, `y`,
#' `fx`, `fy`), used by any of them that doesn't set its own value -- unlike
#' [vg_guide_position()] and [vg_guide_facet()], which set one axis. For
#' scale defaults, see [vg_scale_all()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this guide on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param position `<"top" | "right" | "bottom" | "left" | "both" | boolean | NULL | param()>` The side of the frame on which to place the implicit axis: *top* or *bottom* for *x* or *fx*, or *left* or *right* for *y* or *fy*. (`axis`).
#' @param grid `<boolean | string | param()>` Whether to show a grid aligned with the scale’s ticks. (`grid`).
#' @param aria_label `<string | NULL>` The aria-label attribute on the SVG root. (`ariaLabel`).
#' @param aria_description `<string | NULL>` The aria-description attribute on the SVG root. (`ariaDescription`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family guide functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b) |>
#'   vg_guide_all(grid = TRUE)
vg_guide_all <- function(spec = NULL, position = vg_unset, grid = vg_unset, aria_label = vg_unset, aria_description = vg_unset, ...) {
  context <- "vg_guide_all()"
  suffixes <- c(position = "axis", grid = "grid", aria_label = "ariaLabel", aria_description = "ariaDescription")
  attrs <- prefixed_attrs("", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

