# Generated by data-raw/update-schema.R from mosaic's JSON schema.
# DO NOT EDIT BY HAND -- rerun that script instead.

# Which vg_interactor()/vg_input() types are embedded inside a plot's
# mark list vs. which live in the surrounding layout as standalone
# widgets -- see vg_interactor_placement() in R/interactor.R.
.vg_interactor_types <- c(
  "highlight",
  "intervalX",
  "intervalY",
  "intervalXY",
  "nearestX",
  "nearestY",
  "pan",
  "panX",
  "panY",
  "panZoom",
  "panZoomX",
  "panZoomY",
  "region",
  "toggle",
  "toggleX",
  "toggleY",
  "toggleColor"
)

.vg_input_types <- c(
  "menu",
  "search",
  "slider",
  "table"
)

#' Interactors and inputs: one function per mosaic type
#'
#' Convenience wrappers around [vg_interactor()], one per interactor type
#' (embedded in a plot, e.g. `vg_pan_zoom()`) and input type (a standalone
#' layout widget, e.g. `vg_menu()`) in the mosaic-spec schema -- e.g.
#' `vg_toggle(spec, as = param(sel))` is exactly
#' `vg_interactor(spec, "toggle", as = param(sel))`. See [vg_interactor()]
#' for the general calling convention.
#' @param spec For a plot-embedded interactor: a plot fragment or `vgspec`
#'   to add it to, or `NULL` to start a new plot with just this
#'   interactor. Layout-level inputs don't take a `spec` -- combine them
#'   with plots using [vg_vconcat()]/[vg_hconcat()] instead.
#' @param ... Options for the interactor/input, and/or, for plot-embedded
#'   interactors, plot-level attributes.
#' @rdname vg_interactor
#' @name vg_interactors
NULL

#' @rdname vg_interactor
#' @export
vg_highlight <- function(spec = NULL, ...) vg_interactor(spec, "highlight", ...)

#' @rdname vg_interactor
#' @export
vg_interval_x <- function(spec = NULL, ...) vg_interactor(spec, "intervalX", ...)

#' @rdname vg_interactor
#' @export
vg_interval_y <- function(spec = NULL, ...) vg_interactor(spec, "intervalY", ...)

#' @rdname vg_interactor
#' @export
vg_interval_xy <- function(spec = NULL, ...) vg_interactor(spec, "intervalXY", ...)

#' @rdname vg_interactor
#' @export
vg_nearest_x <- function(spec = NULL, ...) vg_interactor(spec, "nearestX", ...)

#' @rdname vg_interactor
#' @export
vg_nearest_y <- function(spec = NULL, ...) vg_interactor(spec, "nearestY", ...)

#' @rdname vg_interactor
#' @export
vg_pan <- function(spec = NULL, ...) vg_interactor(spec, "pan", ...)

#' @rdname vg_interactor
#' @export
vg_pan_x <- function(spec = NULL, ...) vg_interactor(spec, "panX", ...)

#' @rdname vg_interactor
#' @export
vg_pan_y <- function(spec = NULL, ...) vg_interactor(spec, "panY", ...)

#' @rdname vg_interactor
#' @export
vg_pan_zoom <- function(spec = NULL, ...) vg_interactor(spec, "panZoom", ...)

#' @rdname vg_interactor
#' @export
vg_pan_zoom_x <- function(spec = NULL, ...) vg_interactor(spec, "panZoomX", ...)

#' @rdname vg_interactor
#' @export
vg_pan_zoom_y <- function(spec = NULL, ...) vg_interactor(spec, "panZoomY", ...)

#' @rdname vg_interactor
#' @export
vg_region <- function(spec = NULL, ...) vg_interactor(spec, "region", ...)

#' @rdname vg_interactor
#' @export
vg_toggle <- function(spec = NULL, ...) vg_interactor(spec, "toggle", ...)

#' @rdname vg_interactor
#' @export
vg_toggle_x <- function(spec = NULL, ...) vg_interactor(spec, "toggleX", ...)

#' @rdname vg_interactor
#' @export
vg_toggle_y <- function(spec = NULL, ...) vg_interactor(spec, "toggleY", ...)

#' @rdname vg_interactor
#' @export
vg_toggle_color <- function(spec = NULL, ...) vg_interactor(spec, "toggleColor", ...)

#' @rdname vg_interactor
#' @export
vg_menu <- function(...) vg_interactor(NULL, "menu", ...)

#' @rdname vg_interactor
#' @export
vg_search <- function(...) vg_interactor(NULL, "search", ...)

#' @rdname vg_interactor
#' @export
vg_slider <- function(...) vg_interactor(NULL, "slider", ...)

#' @rdname vg_interactor
#' @export
vg_table <- function(...) vg_interactor(NULL, "table", ...)

