# Generated by data-raw/update-schema.R from mosaic's JSON schema.
# DO NOT EDIT BY HAND -- rerun that script instead.

# Which vg_interactor()/vg_input() types are embedded inside a plot's
# mark list vs. which live in the surrounding layout as standalone
# widgets -- see vg_interactor_placement() in R/interactor.R.
.vg_interactor_types <- c(
  "highlight",
  "intervalX",
  "intervalY",
  "intervalXY",
  "nearestX",
  "nearestY",
  "pan",
  "panX",
  "panY",
  "panZoom",
  "panZoomX",
  "panZoomY",
  "region",
  "toggle",
  "toggleX",
  "toggleY",
  "toggleColor"
)

.vg_input_types <- c(
  "menu",
  "search",
  "slider",
  "table"
)

# One vg_<type>() wrapper per interactor type (embedded in a plot, e.g.,
# vg_pan_zoom()) and input type (a standalone layout widget, e.g.,
# vg_menu()) in the mosaic-spec schema, each with a real named argument
# per option that type accepts -- e.g., vg_toggle(spec, as = param(sel))
# is vg_interactor(spec, "toggle", as = param(sel)) with `as` (and every
# other toggle option) as a real, documented argument.

#' A highlight interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param by `<param()>` The input selection.
#' @param fill `<string>` The fill color of deemphasized marks.
#' @param fill_opacity `<number>` The fill opacity of deemphasized marks.
#' @param opacity `<number>` The overall opacity of deemphasized marks.
#' @param stroke `<string>` The stroke color of deemphasized marks.
#' @param stroke_opacity `<number>` The stroke opacity of deemphasized marks.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_highlight <- function(spec = NULL, by = vg_unset, fill = vg_unset, fill_opacity = vg_unset, opacity = vg_unset, stroke = vg_unset, stroke_opacity = vg_unset, ...) {
  vg_interactor_(spec, "highlight", by = by, fill = fill, fillOpacity = fill_opacity, opacity = opacity, stroke = stroke, strokeOpacity = stroke_opacity, ...)
}

#' An intervalX interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param brush `<list>` CSS styles for the brush (SVG `rect`) element.
#' @param field `<string>` The name of the field (database column) over which the interval selection should be defined.
#' @param peers `<boolean>` A flag indicating if peer (sibling) marks are excluded when cross-filtering (default `true`).
#' @param pixel_size `<number>` The size of an interactive pixel (default `1`).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_interval_x <- function(spec = NULL, as = vg_unset, brush = vg_unset, field = vg_unset, peers = vg_unset, pixel_size = vg_unset, ...) {
  vg_interactor_(spec, "intervalX", as = as, brush = brush, field = field, peers = peers, pixelSize = pixel_size, ...)
}

#' An intervalY interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param brush `<list>` CSS styles for the brush (SVG `rect`) element.
#' @param field `<string>` The name of the field (database column) over which the interval selection should be defined.
#' @param peers `<boolean>` A flag indicating if peer (sibling) marks are excluded when cross-filtering (default `true`).
#' @param pixel_size `<number>` The size of an interactive pixel (default `1`).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_interval_y <- function(spec = NULL, as = vg_unset, brush = vg_unset, field = vg_unset, peers = vg_unset, pixel_size = vg_unset, ...) {
  vg_interactor_(spec, "intervalY", as = as, brush = brush, field = field, peers = peers, pixelSize = pixel_size, ...)
}

#' An intervalXY interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param brush `<list>` CSS styles for the brush (SVG `rect`) element.
#' @param peers `<boolean>` A flag indicating if peer (sibling) marks are excluded when cross-filtering (default `true`).
#' @param pixel_size `<number>` The size of an interactive pixel (default `1`).
#' @param xfield `<string>` The name of the field (database column) over which the `x`-component of the interval selection should be defined.
#' @param yfield `<string>` The name of the field (database column) over which the `y`-component of the interval selection should be defined.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_interval_xy <- function(spec = NULL, as = vg_unset, brush = vg_unset, peers = vg_unset, pixel_size = vg_unset, xfield = vg_unset, yfield = vg_unset, ...) {
  vg_interactor_(spec, "intervalXY", as = as, brush = brush, peers = peers, pixelSize = pixel_size, xfield = xfield, yfield = yfield, ...)
}

#' A nearestX interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param channels `<character vector>` The encoding channels whose domain values should be selected.
#' @param fields `<character vector>` The fields (database column names) to use in generated selection clause predicates.
#' @param max_radius `<number>` The maximum radius of a nearest selection (default 40).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_nearest_x <- function(spec = NULL, as = vg_unset, channels = vg_unset, fields = vg_unset, max_radius = vg_unset, ...) {
  vg_interactor_(spec, "nearestX", as = as, channels = channels, fields = fields, maxRadius = max_radius, ...)
}

#' A nearestY interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param channels `<character vector>` The encoding channels whose domain values should be selected.
#' @param fields `<character vector>` The fields (database column names) to use in generated selection clause predicates.
#' @param max_radius `<number>` The maximum radius of a nearest selection (default 40).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_nearest_y <- function(spec = NULL, as = vg_unset, channels = vg_unset, fields = vg_unset, max_radius = vg_unset, ...) {
  vg_interactor_(spec, "nearestY", as = as, channels = channels, fields = fields, maxRadius = max_radius, ...)
}

#' A pan interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param x `<param()>` The output selection for the `x` domain.
#' @param xfield `<string>` The name of the field (database column) over which the `x`-component of the interval selection should be defined.
#' @param y `<param()>` The output selection for the `y` domain.
#' @param yfield `<string>` The name of the field (database column) over which the `y`-component of the interval selection should be defined.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_pan <- function(spec = NULL, x = vg_unset, xfield = vg_unset, y = vg_unset, yfield = vg_unset, ...) {
  vg_interactor_(spec, "pan", x = x, xfield = xfield, y = y, yfield = yfield, ...)
}

#' A panX interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param x `<param()>` The output selection for the `x` domain.
#' @param xfield `<string>` The name of the field (database column) over which the `x`-component of the interval selection should be defined.
#' @param y `<param()>` The output selection for the `y` domain.
#' @param yfield `<string>` The name of the field (database column) over which the `y`-component of the interval selection should be defined.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_pan_x <- function(spec = NULL, x = vg_unset, xfield = vg_unset, y = vg_unset, yfield = vg_unset, ...) {
  vg_interactor_(spec, "panX", x = x, xfield = xfield, y = y, yfield = yfield, ...)
}

#' A panY interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param x `<param()>` The output selection for the `x` domain.
#' @param xfield `<string>` The name of the field (database column) over which the `x`-component of the interval selection should be defined.
#' @param y `<param()>` The output selection for the `y` domain.
#' @param yfield `<string>` The name of the field (database column) over which the `y`-component of the interval selection should be defined.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_pan_y <- function(spec = NULL, x = vg_unset, xfield = vg_unset, y = vg_unset, yfield = vg_unset, ...) {
  vg_interactor_(spec, "panY", x = x, xfield = xfield, y = y, yfield = yfield, ...)
}

#' A panZoom interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param x `<param()>` The output selection for the `x` domain.
#' @param xfield `<string>` The name of the field (database column) over which the `x`-component of the interval selection should be defined.
#' @param y `<param()>` The output selection for the `y` domain.
#' @param yfield `<string>` The name of the field (database column) over which the `y`-component of the interval selection should be defined.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_pan_zoom <- function(spec = NULL, x = vg_unset, xfield = vg_unset, y = vg_unset, yfield = vg_unset, ...) {
  vg_interactor_(spec, "panZoom", x = x, xfield = xfield, y = y, yfield = yfield, ...)
}

#' A panZoomX interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param x `<param()>` The output selection for the `x` domain.
#' @param xfield `<string>` The name of the field (database column) over which the `x`-component of the interval selection should be defined.
#' @param y `<param()>` The output selection for the `y` domain.
#' @param yfield `<string>` The name of the field (database column) over which the `y`-component of the interval selection should be defined.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_pan_zoom_x <- function(spec = NULL, x = vg_unset, xfield = vg_unset, y = vg_unset, yfield = vg_unset, ...) {
  vg_interactor_(spec, "panZoomX", x = x, xfield = xfield, y = y, yfield = yfield, ...)
}

#' A panZoomY interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param x `<param()>` The output selection for the `x` domain.
#' @param xfield `<string>` The name of the field (database column) over which the `x`-component of the interval selection should be defined.
#' @param y `<param()>` The output selection for the `y` domain.
#' @param yfield `<string>` The name of the field (database column) over which the `y`-component of the interval selection should be defined.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_pan_zoom_y <- function(spec = NULL, x = vg_unset, xfield = vg_unset, y = vg_unset, yfield = vg_unset, ...) {
  vg_interactor_(spec, "panZoomY", x = x, xfield = xfield, y = y, yfield = yfield, ...)
}

#' A rectangular region interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param brush `<list>` CSS styles for the brush (SVG `rect`) element.
#' @param channels `<character vector>` The encoding channels whose domain values should be selected.
#' @param peers `<boolean>` A flag indicating if peer (sibling) marks are excluded when cross-filtering (default `true`).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_region <- function(spec = NULL, as = vg_unset, brush = vg_unset, channels = vg_unset, peers = vg_unset, ...) {
  vg_interactor_(spec, "region", as = as, brush = brush, channels = channels, peers = peers, ...)
}

#' A toggle interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param channels `<character vector>` The encoding channels whose domain values should be selected.
#' @param peers `<boolean>` A flag indicating if peer (sibling) marks are excluded when cross-filtering (default `true`).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_toggle <- function(spec = NULL, as = vg_unset, channels = vg_unset, peers = vg_unset, ...) {
  vg_interactor_(spec, "toggle", as = as, channels = channels, peers = peers, ...)
}

#' A toggleX interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param peers `<boolean>` A flag indicating if peer (sibling) marks are excluded when cross-filtering (default `true`).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_toggle_x <- function(spec = NULL, as = vg_unset, peers = vg_unset, ...) {
  vg_interactor_(spec, "toggleX", as = as, peers = peers, ...)
}

#' A toggleY interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param peers `<boolean>` A flag indicating if peer (sibling) marks are excluded when cross-filtering (default `true`).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_toggle_y <- function(spec = NULL, as = vg_unset, peers = vg_unset, ...) {
  vg_interactor_(spec, "toggleY", as = as, peers = peers, ...)
}

#' A toggleColor interactor.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to add this interactor to, or `NULL` to start a new plot with just this interactor.
#' @param as `<param()>` The output selection.
#' @param peers `<boolean>` A flag indicating if peer (sibling) marks are excluded when cross-filtering (default `true`).
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_toggle_color <- function(spec = NULL, as = vg_unset, peers = vg_unset, ...) {
  vg_interactor_(spec, "toggleColor", as = as, peers = peers, ...)
}

#' A menu input component.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param as `<param()>` The output selection.
#' @param column `<string>` The name of a database column from which to pull menu options.
#' @param field `<string>` The name of the field (database column) over which the interval selection should be defined.
#' @param filter_by `<param()>` A selection to filter the database table indicated by the `from` property.
#' @param from `<string>` The name of a database table to use as a data source for this widget.
#' @param label `<string>` A text label for this input.
#' @param list_match `<"any" | "all">` Required if the database column is an list, this property determines how to match the selected menu option against the list values.
#' @param options `<vector>` An array of menu options, as literal values or option objects.
#' @param value `<any>` The initial selected menu value.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_menu <- function(as = vg_unset, column = vg_unset, field = vg_unset, filter_by = vg_unset, from = vg_unset, label = vg_unset, list_match = vg_unset, options = vg_unset, value = vg_unset, ...) {
  vg_interactor_(NULL, "menu", as = as, column = column, field = field, filterBy = filter_by, from = from, label = label, listMatch = list_match, options = options, value = value, ...)
}

#' A search input component.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param as `<param()>` The output selection.
#' @param column `<string>` The name of a database column from which to pull menu options.
#' @param field `<string>` The name of the field (database column) over which the interval selection should be defined.
#' @param filter_by `<param()>` A selection to filter the database table indicated by the `from` property.
#' @param from `<string>` The name of a database table to use as a data source for this widget.
#' @param label `<string>` A text label for this input.
#' @param type `<"contains" | "prefix" | "suffix" | "regexp">` The type of text search query to perform.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_search <- function(as = vg_unset, column = vg_unset, field = vg_unset, filter_by = vg_unset, from = vg_unset, label = vg_unset, type = vg_unset, ...) {
  vg_interactor_(NULL, "search", as = as, column = column, field = field, filterBy = filter_by, from = from, label = label, type = type, ...)
}

#' A slider input component.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param as `<param()>` The output selection.
#' @param column `<string>` The name of a database column from which to pull menu options.
#' @param field `<string>` The name of the field (database column) over which the interval selection should be defined.
#' @param filter_by `<param()>` A selection to filter the database table indicated by the `from` property.
#' @param from `<string>` The name of a database table to use as a data source for this widget.
#' @param label `<string>` A text label for this input.
#' @param max `<number>` The maximum slider value.
#' @param min `<number>` The minimum slider value.
#' @param select `<"point" | "interval">` The type of selection clause predicate to generate if the **as** option is a Selection.
#' @param step `<number>` The slider step, the amount to increment between consecutive values.
#' @param value `<any>` The initial selected menu value.
#' @param width `<number>` The width of the slider in screen pixels.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_slider <- function(as = vg_unset, column = vg_unset, field = vg_unset, filter_by = vg_unset, from = vg_unset, label = vg_unset, max = vg_unset, min = vg_unset, select = vg_unset, step = vg_unset, value = vg_unset, width = vg_unset, ...) {
  vg_interactor_(NULL, "slider", as = as, column = column, field = field, filterBy = filter_by, from = from, label = label, max = max, min = min, select = select, step = step, value = value, width = width, ...)
}

#' A table grid view component.
#'
#' See [vg_value_types] for what the `<...>` notation below (`column`, `param()`, ...) means.
#'
#' @param align `<list>` An object of per-column alignment values.
#' @param as `<param()>` The output selection.
#' @param columns `<character vector>` A list of column names to include in the table grid.
#' @param filter_by `<param()>` A selection to filter the database table indicated by the `from` property.
#' @param from `<string>` The name of a database table to use as a data source for this widget.
#' @param height `<number>` The height of the table widget, in pixels.
#' @param max_width `<number>` The maximum width of the table widget, in pixels.
#' @param row_batch `<number>` The number of rows load in a new batch upon table scroll.
#' @param width `<number>` The width of the slider in screen pixels.
#' @param ... Additional options or plot-level attributes.
#' @family interactor functions
#' @export
vg_table <- function(align = vg_unset, as = vg_unset, columns = vg_unset, filter_by = vg_unset, from = vg_unset, height = vg_unset, max_width = vg_unset, row_batch = vg_unset, width = vg_unset, ...) {
  vg_interactor_(NULL, "table", align = align, as = as, columns = columns, filterBy = filter_by, from = from, height = height, maxWidth = max_width, rowBatch = row_batch, width = width, ...)
}

