#' Add a mark (a single visual layer, e.g. points or a line) to a plot
#'
#' This is the generic, low-level constructor that the `vg_dot()`,
#' `vg_line_y()`, etc. convenience functions -- one per mark type in
#' mosaic's own JSON schema, generated by `data-raw/update-schema.R` into
#' `R/marks-generated.R` -- are built on top of.
#'
#' @param spec A plot fragment or `vgspec` to add this mark to, or `NULL` to
#'   start a new plot with just this mark.
#' @param mark The mosaic mark type, e.g. `"dot"`, `"lineY"`.
#' @param ... Encodings (e.g. `x = ~var1`), mark options, and/or plot-level
#'   attributes (`width =`, `name =`, ...). See [vg_plot()] for how
#'   plot-level attributes from multiple marks are combined.
#' @export
vg_mark <- function(spec = NULL, mark, ...) {
  split <- split_plot_args(list(...))

  mark_obj <- structure(
    list(mark = mark, encodings = split$local_args),
    class = "vg_mark"
  )

  fragment <- as_vg_plot_fragment(spec)
  fragment$items <- c(fragment$items, list(mark_obj))
  fragment$attrs <- merge_attrs(fragment$attrs, split$plot_attrs, context = paste0("mark `", mark, "`"))

  update_layout(spec, fragment)
}

# Shared by every generated vg_<mark>() wrapper (R/marks-generated.R):
# drops whichever named arguments the caller left at their vg_unset
# default (i.e. didn't actually supply) before dispatching to vg_mark().
#
# The mark type is `.vg_mark` (not `mark`) so it can't collide with a mark
# property forwarded through `...` by exact-name argument matching -- no
# current mark has a property literally called "mark" (it's excluded as
# the schema's own discriminant key), but vg_interactor_()'s analogous
# parameter name did collide with a real property (Search's own "type"),
# so this is named defensively too.
vg_mark_ <- function(spec, .vg_mark, ...) {
  do.call(vg_mark, c(list(spec = spec, mark = .vg_mark), drop_unset(list(...))))
}

#' @export
print.vg_mark <- function(x, ...) {
  cat("<vg_mark:", x$mark, ">\n")
  if (length(x$encodings)) {
    str_enc <- vapply(x$encodings, deparse_short, character(1))
    cat(paste0("  ", names(x$encodings), " = ", str_enc, collapse = "\n"), "\n")
  }
  invisible(x)
}
