# Generated by data-raw/update-schema.R from mosaic's JSON schema.
# DO NOT EDIT BY HAND -- rerun that script instead.

#' Marks: one function per mosaic mark type
#'
#' Convenience wrappers around [vg_mark()], one per mark type in the
#' mosaic-spec schema -- e.g. `vg_dot(spec, x = ~a, y = ~b)` is exactly
#' `vg_mark(spec, "dot", x = ~a, y = ~b)`. See [vg_mark()] for the general
#' calling convention (encodings, mark options, and plot-level attributes
#' can all be passed via `...`).
#' @param spec A plot fragment or `vgspec` to add this mark to, or `NULL`
#'   to start a new plot with just this mark.
#' @param ... Encodings, mark options, and/or plot-level attributes.
#' @rdname vg_mark
#' @name vg_marks
NULL

#' @rdname vg_mark
#' @export
vg_area <- function(spec = NULL, ...) vg_mark(spec, "area", ...)

#' @rdname vg_mark
#' @export
vg_area_x <- function(spec = NULL, ...) vg_mark(spec, "areaX", ...)

#' @rdname vg_mark
#' @export
vg_area_y <- function(spec = NULL, ...) vg_mark(spec, "areaY", ...)

#' @rdname vg_mark
#' @export
vg_arrow <- function(spec = NULL, ...) vg_mark(spec, "arrow", ...)

#' @rdname vg_mark
#' @export
vg_axis_fx <- function(spec = NULL, ...) vg_mark(spec, "axisFx", ...)

#' @rdname vg_mark
#' @export
vg_axis_fy <- function(spec = NULL, ...) vg_mark(spec, "axisFy", ...)

#' @rdname vg_mark
#' @export
vg_axis_x <- function(spec = NULL, ...) vg_mark(spec, "axisX", ...)

#' @rdname vg_mark
#' @export
vg_axis_y <- function(spec = NULL, ...) vg_mark(spec, "axisY", ...)

#' @rdname vg_mark
#' @export
vg_bar_x <- function(spec = NULL, ...) vg_mark(spec, "barX", ...)

#' @rdname vg_mark
#' @export
vg_bar_y <- function(spec = NULL, ...) vg_mark(spec, "barY", ...)

#' @rdname vg_mark
#' @export
vg_cell <- function(spec = NULL, ...) vg_mark(spec, "cell", ...)

#' @rdname vg_mark
#' @export
vg_cell_x <- function(spec = NULL, ...) vg_mark(spec, "cellX", ...)

#' @rdname vg_mark
#' @export
vg_cell_y <- function(spec = NULL, ...) vg_mark(spec, "cellY", ...)

#' @rdname vg_mark
#' @export
vg_circle <- function(spec = NULL, ...) vg_mark(spec, "circle", ...)

#' @rdname vg_mark
#' @export
vg_contour <- function(spec = NULL, ...) vg_mark(spec, "contour", ...)

#' @rdname vg_mark
#' @export
vg_delaunay_link <- function(spec = NULL, ...) vg_mark(spec, "delaunayLink", ...)

#' @rdname vg_mark
#' @export
vg_delaunay_mesh <- function(spec = NULL, ...) vg_mark(spec, "delaunayMesh", ...)

#' @rdname vg_mark
#' @export
vg_dense_line <- function(spec = NULL, ...) vg_mark(spec, "denseLine", ...)

#' @rdname vg_mark
#' @export
vg_density <- function(spec = NULL, ...) vg_mark(spec, "density", ...)

#' @rdname vg_mark
#' @export
vg_density_x <- function(spec = NULL, ...) vg_mark(spec, "densityX", ...)

#' @rdname vg_mark
#' @export
vg_density_y <- function(spec = NULL, ...) vg_mark(spec, "densityY", ...)

#' @rdname vg_mark
#' @export
vg_dot <- function(spec = NULL, ...) vg_mark(spec, "dot", ...)

#' @rdname vg_mark
#' @export
vg_dot_x <- function(spec = NULL, ...) vg_mark(spec, "dotX", ...)

#' @rdname vg_mark
#' @export
vg_dot_y <- function(spec = NULL, ...) vg_mark(spec, "dotY", ...)

#' @rdname vg_mark
#' @export
vg_errorbar_x <- function(spec = NULL, ...) vg_mark(spec, "errorbarX", ...)

#' @rdname vg_mark
#' @export
vg_errorbar_y <- function(spec = NULL, ...) vg_mark(spec, "errorbarY", ...)

#' @rdname vg_mark
#' @export
vg_frame <- function(spec = NULL, ...) vg_mark(spec, "frame", ...)

#' @rdname vg_mark
#' @export
vg_geo <- function(spec = NULL, ...) vg_mark(spec, "geo", ...)

#' @rdname vg_mark
#' @export
vg_graticule <- function(spec = NULL, ...) vg_mark(spec, "graticule", ...)

#' @rdname vg_mark
#' @export
vg_grid_fx <- function(spec = NULL, ...) vg_mark(spec, "gridFx", ...)

#' @rdname vg_mark
#' @export
vg_grid_fy <- function(spec = NULL, ...) vg_mark(spec, "gridFy", ...)

#' @rdname vg_mark
#' @export
vg_grid_x <- function(spec = NULL, ...) vg_mark(spec, "gridX", ...)

#' @rdname vg_mark
#' @export
vg_grid_y <- function(spec = NULL, ...) vg_mark(spec, "gridY", ...)

#' @rdname vg_mark
#' @export
vg_heatmap <- function(spec = NULL, ...) vg_mark(spec, "heatmap", ...)

#' @rdname vg_mark
#' @export
vg_hexagon <- function(spec = NULL, ...) vg_mark(spec, "hexagon", ...)

#' @rdname vg_mark
#' @export
vg_hexbin <- function(spec = NULL, ...) vg_mark(spec, "hexbin", ...)

#' @rdname vg_mark
#' @export
vg_hexgrid <- function(spec = NULL, ...) vg_mark(spec, "hexgrid", ...)

#' @rdname vg_mark
#' @export
vg_hull <- function(spec = NULL, ...) vg_mark(spec, "hull", ...)

#' @rdname vg_mark
#' @export
vg_image <- function(spec = NULL, ...) vg_mark(spec, "image", ...)

#' @rdname vg_mark
#' @export
vg_line <- function(spec = NULL, ...) vg_mark(spec, "line", ...)

#' @rdname vg_mark
#' @export
vg_line_x <- function(spec = NULL, ...) vg_mark(spec, "lineX", ...)

#' @rdname vg_mark
#' @export
vg_line_y <- function(spec = NULL, ...) vg_mark(spec, "lineY", ...)

#' @rdname vg_mark
#' @export
vg_link <- function(spec = NULL, ...) vg_mark(spec, "link", ...)

#' @rdname vg_mark
#' @export
vg_raster <- function(spec = NULL, ...) vg_mark(spec, "raster", ...)

#' @rdname vg_mark
#' @export
vg_raster_tile <- function(spec = NULL, ...) vg_mark(spec, "rasterTile", ...)

#' @rdname vg_mark
#' @export
vg_rect <- function(spec = NULL, ...) vg_mark(spec, "rect", ...)

#' @rdname vg_mark
#' @export
vg_rect_x <- function(spec = NULL, ...) vg_mark(spec, "rectX", ...)

#' @rdname vg_mark
#' @export
vg_rect_y <- function(spec = NULL, ...) vg_mark(spec, "rectY", ...)

#' @rdname vg_mark
#' @export
vg_regression_y <- function(spec = NULL, ...) vg_mark(spec, "regressionY", ...)

#' @rdname vg_mark
#' @export
vg_rule_x <- function(spec = NULL, ...) vg_mark(spec, "ruleX", ...)

#' @rdname vg_mark
#' @export
vg_rule_y <- function(spec = NULL, ...) vg_mark(spec, "ruleY", ...)

#' @rdname vg_mark
#' @export
vg_sphere <- function(spec = NULL, ...) vg_mark(spec, "sphere", ...)

#' @rdname vg_mark
#' @export
vg_spike <- function(spec = NULL, ...) vg_mark(spec, "spike", ...)

#' @rdname vg_mark
#' @export
vg_text <- function(spec = NULL, ...) vg_mark(spec, "text", ...)

#' @rdname vg_mark
#' @export
vg_text_x <- function(spec = NULL, ...) vg_mark(spec, "textX", ...)

#' @rdname vg_mark
#' @export
vg_text_y <- function(spec = NULL, ...) vg_mark(spec, "textY", ...)

#' @rdname vg_mark
#' @export
vg_tick_x <- function(spec = NULL, ...) vg_mark(spec, "tickX", ...)

#' @rdname vg_mark
#' @export
vg_tick_y <- function(spec = NULL, ...) vg_mark(spec, "tickY", ...)

#' @rdname vg_mark
#' @export
vg_vector <- function(spec = NULL, ...) vg_mark(spec, "vector", ...)

#' @rdname vg_mark
#' @export
vg_vector_x <- function(spec = NULL, ...) vg_mark(spec, "vectorX", ...)

#' @rdname vg_mark
#' @export
vg_vector_y <- function(spec = NULL, ...) vg_mark(spec, "vectorY", ...)

#' @rdname vg_mark
#' @export
vg_voronoi <- function(spec = NULL, ...) vg_mark(spec, "voronoi", ...)

#' @rdname vg_mark
#' @export
vg_voronoi_mesh <- function(spec = NULL, ...) vg_mark(spec, "voronoiMesh", ...)

#' @rdname vg_mark
#' @export
vg_waffle_x <- function(spec = NULL, ...) vg_mark(spec, "waffleX", ...)

#' @rdname vg_mark
#' @export
vg_waffle_y <- function(spec = NULL, ...) vg_mark(spec, "waffleY", ...)

