#' Add a mark (a single visual layer, e.g. points or a line) to a plot
#'
#' This is the generic, low-level constructor that the `vg_mark_dot()`,
#' `vg_mark_line_y()`, etc. convenience functions -- one per mark type in
#' mosaic's own JSON schema, generated by `data-raw/update-schema.R` into
#' `R/marks-generated.R` -- are built on top of.
#'
#' @param spec A plot fragment or `vgspec` to add this mark to, `NULL` to
#'   start a new plot with just this mark, or a data frame -- shorthand for
#'   `vg_create() |> vg_data(data = spec) |> vg_mark_<mark>(...)`, i.e.
#'   starting a brand-new spec with `spec` registered as its data source
#'   (named per [vg_data()]) and used automatically as this mark's own
#'   `data_from` -- e.g. `some_data |> vg_mark_dot(x = ~a, y = ~b)`. A
#'   `data_from =` string given explicitly names the registered source
#'   instead of the [vg_data()] default (handy since it's also what later
#'   marks in the chain need for their own `data_from =`); giving anything
#'   else there (a literal vector, a [param()]) doesn't make sense for a
#'   single data frame and is left alone, meant for a plot fragment/`vgspec`
#'   `spec` instead. Only useful for the *first* mark in a chain: by the
#'   time a second mark is piped in, `spec` is already a plot fragment, not
#'   a data frame.
#' @param mark The mosaic mark type, e.g. `"dot"`, `"lineY"`.
#' @param ... Encodings (e.g. `x = ~var1`), mark options, and/or plot-level
#'   attributes (`width =`, `name =`, ...). See [vg_plot()] for how
#'   plot-level attributes from multiple marks are combined.
#' @export
vg_mark <- function(spec = NULL, mark, ...) {
  args <- list(...)
  if (is.data.frame(spec)) {
    given_name <- args$data_from
    has_given_name <- is.character(given_name) && length(given_name) == 1
    data_name <- if (has_given_name) given_name else auto_data_name(vg_create())
    spec <- vg_data(vg_create(), name = data_name, data = spec)
    if (!has_given_name) args$data_from <- data_name
  }

  split <- split_plot_args(args, protect = .vg_mark_own_props[[mark]])

  mark_obj <- structure(
    list(mark = mark, encodings = split$local_args),
    class = "vg_mark"
  )

  fragment <- as_vg_plot_fragment(spec)
  fragment$items <- c(fragment$items, list(mark_obj))
  fragment$attrs <- merge_attrs(fragment$attrs, split$plot_attrs, context = paste0("mark `", mark, "`"))

  update_layout(spec, fragment)
}

# Shared by every generated vg_mark_<mark>() wrapper (R/marks-generated.R):
# drops whichever named arguments the caller left at their vg_unset
# default (i.e. didn't actually supply) before dispatching to vg_mark().
#
# Safe to name this parameter `mark` (matching vg_mark()'s own parameter):
# "mark" is always excluded from a mark's own generated properties (it's
# the schema's discriminant key for the mark itself), so no mark ever has
# a same-named option that could collide by exact-name argument matching
# the way vg_interactor_()'s equivalent parameter did (Search's own "type"
# option) -- see vg_interactor()'s docs for that story.
vg_mark_ <- function(spec, mark, ...) {
  do.call(vg_mark, c(list(spec = spec, mark = mark), drop_unset(list(...))))
}

#' @export
print.vg_mark <- function(x, ...) {
  cat("<vg_mark:", x$mark, ">\n")
  if (length(x$encodings)) {
    str_enc <- vapply(x$encodings, deparse_short, character(1))
    cat(paste0("  ", names(x$encodings), " = ", str_enc, collapse = "\n"), "\n")
  }
  invisible(x)
}
