# Generated by data-raw/update-schema.R from mosaic's JSON schema.
# DO NOT EDIT BY HAND -- rerun that script instead.
#
# One vg_scale_*() constructor per scale channel/family in mosaic-spec's
# PlotAttributes -- see data-raw/update-schema.R's own comments for how
# properties are classified into these.

#' @include utils.R
NULL

# Which InsetLeft/InsetRight vs InsetTop/InsetBottom pair applies to which
# `which` value -- used by add_inset_attrs() (R/utils.R).
vg_inset_side_suffixes <- list(
  x = c(inset_left = "InsetLeft", inset_right = "InsetRight"),
  y = c(inset_top = "InsetTop", inset_bottom = "InsetBottom"),
  fx = c(inset_left = "InsetLeft", inset_right = "InsetRight"),
  fy = c(inset_top = "InsetTop", inset_bottom = "InsetBottom")
)

vg_position_counterpart <- c(x = "y", y = "x", fx = "fy", fy = "fx")

#' Set position scale properties (x or y)
#'
#' `vg_scale_x()` and `vg_scale_y()` set the properties of a plot's x and y
#' scales: type, domain, range, and so on (Mosaic's `xScale`, `xDomain`, ...
#' attributes, and the same for `y`). The same attributes can also be given
#' to [vg_plot()] or [vg_attributes()], as `x_domain =` and so on.
#' `vg_scale_position()` is the general form, taking `which = "x"` or `"y"`.
#'
#' Like [vg_plot()], these can be piped in anywhere among a plot's marks and
#' interactors. For the facet scales (`fx`/`fy`), see [vg_scale_facet()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param which Which position scale this sets: `"x"` or `"y"`.
#' @param type `<"linear" | "pow" | "sqrt" | "log" | "symlog" | "utc" | "time" | "point" | "band" | "threshold" | ... | NULL | param()>` The *x* scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`xScale`/`yScale`).
#' @param domain `<vector | "Fixed" | param()>` The extent of the scale’s inputs (abstract values). (`xDomain`/`yDomain`).
#' @param range `<vector | "Fixed" | param()>` The extent of the scale’s outputs (visual values). (`xRange`/`yRange`).
#' @param nice `<boolean | number | "day"/"week"/"month"/... | param()>` If true, or a tick count or interval, extend the domain to nice round values. (`xNice`/`yNice`).
#' @param zero `<boolean | param()>` Whether the **domain** must include zero. (`xZero`/`yZero`).
#' @param reverse `<boolean | param()>` Whether to reverse the scale’s encoding; equivalent to reversing either the **domain** or **range**. (`xReverse`/`yReverse`).
#' @param clamp `<boolean | param()>` If true, values below the domain minimum are treated as the domain minimum, and values above the domain maximum are treated as the domain maximum. (`xClamp`/`yClamp`).
#' @param round `<boolean | param()>` If true, round the output value to the nearest integer (pixel); useful for crisp edges when rendering. (`xRound`/`yRound`).
#' @param padding `<number | param()>` For *band* scales, how much of the **range** to reserve to separate adjacent bands; defaults to 0.1 (10%). (`xPadding`/`yPadding`).
#' @param padding_inner `<number | param()>` For a *band* scale, how much of the range to reserve to separate adjacent bands. (`xPaddingInner`/`yPaddingInner`).
#' @param padding_outer `<number | param()>` For a *band* scale, how much of the range to reserve to inset first and last bands. (`xPaddingOuter`/`yPaddingOuter`).
#' @param align `<number | param()>` How to distribute unused space in the **range** for *point* and *band* scales. (`xAlign`/`yAlign`).
#' @param inset `<number | param()>` Shorthand to set the same default for all four insets: **insetTop**, **insetRight**, **insetBottom**, and **insetLeft**. (`xInset`/`yInset`).
#' @param base `<number | param()>` A log scale’s base; defaults to 10. (`xBase`/`yBase`).
#' @param exponent `<number | param()>` A power scale’s exponent (*e.g.*, 0.5 for sqrt); defaults to 1 for a linear scale. (`xExponent`/`yExponent`).
#' @param constant `<number | param()>` A symlog scale’s constant, expressing the magnitude of the linear region around the origin; defaults to 1. (`xConstant`/`yConstant`).
#' @param percent `<boolean | param()>` If true, shorthand for a transform suitable for percentages, mapping proportions in 0, 1 to 0, 100. (`xPercent`/`yPercent`).
#' @param inset_left,inset_right `<number | param()>` Pixel inset at the left/right end of the range; only meaningful for `which = "x"` (`xInsetLeft`/`xInsetRight`).
#' @param inset_top,inset_bottom `<number | param()>` Pixel inset at the top/bottom end of the range; only meaningful for `which = "y"` (`yInsetTop`/`yInsetBottom`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b) |>
#'   vg_scale_x(type = "log") |>
#'   vg_scale_y(zero = TRUE, nice = TRUE)
vg_scale_position <- function(spec = NULL, which = c("x", "y"), type = vg_unset, domain = vg_unset, range = vg_unset, nice = vg_unset, zero = vg_unset, reverse = vg_unset, clamp = vg_unset, round = vg_unset, padding = vg_unset, padding_inner = vg_unset, padding_outer = vg_unset, align = vg_unset, inset = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, inset_left = vg_unset, inset_right = vg_unset, inset_top = vg_unset, inset_bottom = vg_unset, ...) {
  which <- match.arg(which)
  context <- paste0("vg_scale_", which, "()")
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", nice = "Nice", zero = "Zero", reverse = "Reverse", clamp = "Clamp", round = "Round", padding = "Padding", padding_inner = "PaddingInner", padding_outer = "PaddingOuter", align = "Align", inset = "Inset", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent")
  attrs <- prefixed_attrs(which, suffixes, environment())
  attrs <- add_inset_attrs(attrs, which, environment(), context)
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_scale_position
#' @export
vg_scale_x <- wrapper_function(vg_scale_position, which = "x", drop = c("inset_top", "inset_bottom"))

#' @rdname vg_scale_position
#' @export
vg_scale_y <- wrapper_function(vg_scale_position, which = "y", drop = c("inset_left", "inset_right"))

#' Set facet scale properties (fx or fy)
#'
#' `vg_scale_fx()` and `vg_scale_fy()` set the properties of a plot's facet
#' scales (`fxDomain`, `fxPadding`, ..., and the same for `fy`). Facet scales
#' are always band scales, so they have fewer properties than
#' [vg_scale_position()] (no `type`, `nice`, `zero`, `clamp`, ...).
#' `vg_scale_facet()` is the general form, taking `which = "fx"` or `"fy"`.
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param which Which facet scale this sets: `"fx"` or `"fy"`.
#' @param domain `<vector | "Fixed" | param()>` The extent of the scale’s inputs (abstract values). (`fxDomain`/`fyDomain`).
#' @param range `<vector | "Fixed" | param()>` The extent of the scale’s outputs (visual values). (`fxRange`/`fyRange`).
#' @param reverse `<boolean | param()>` Whether to reverse the scale’s encoding; equivalent to reversing either the **domain** or **range**. (`fxReverse`/`fyReverse`).
#' @param round `<boolean | param()>` If true, round the output value to the nearest integer (pixel); useful for crisp edges when rendering. (`fxRound`/`fyRound`).
#' @param padding `<number | param()>` For *band* scales, how much of the **range** to reserve to separate adjacent bands; defaults to 0.1 (10%). (`fxPadding`/`fyPadding`).
#' @param padding_inner `<number | param()>` For a *band* scale, how much of the range to reserve to separate adjacent bands. (`fxPaddingInner`/`fyPaddingInner`).
#' @param padding_outer `<number | param()>` For a *band* scale, how much of the range to reserve to inset first and last bands. (`fxPaddingOuter`/`fyPaddingOuter`).
#' @param align `<number | param()>` How to distribute unused space in the **range** for *point* and *band* scales. (`fxAlign`/`fyAlign`).
#' @param inset `<number | param()>` Shorthand to set the same default for all four insets: **insetTop**, **insetRight**, **insetBottom**, and **insetLeft**. (`fxInset`/`fyInset`).
#' @param inset_left,inset_right `<number | param()>` Pixel inset at the left/right end of the range; only meaningful for `which = "fx"` (`fxInsetLeft`/`fxInsetRight`).
#' @param inset_top,inset_bottom `<number | param()>` Pixel inset at the top/bottom end of the range; only meaningful for `which = "fy"` (`fyInsetTop`/`fyInsetBottom`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, fx = ~g) |>
#'   vg_scale_fx(padding = 0.1)
vg_scale_facet <- function(spec = NULL, which = c("fx", "fy"), domain = vg_unset, range = vg_unset, reverse = vg_unset, round = vg_unset, padding = vg_unset, padding_inner = vg_unset, padding_outer = vg_unset, align = vg_unset, inset = vg_unset, inset_left = vg_unset, inset_right = vg_unset, inset_top = vg_unset, inset_bottom = vg_unset, ...) {
  which <- match.arg(which)
  context <- paste0("vg_scale_", which, "()")
  suffixes <- c(domain = "Domain", range = "Range", reverse = "Reverse", round = "Round", padding = "Padding", padding_inner = "PaddingInner", padding_outer = "PaddingOuter", align = "Align", inset = "Inset")
  attrs <- prefixed_attrs(which, suffixes, environment())
  attrs <- add_inset_attrs(attrs, which, environment(), context)
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_scale_facet
#' @export
vg_scale_fx <- wrapper_function(vg_scale_facet, which = "fx", drop = c("inset_top", "inset_bottom"))

#' @rdname vg_scale_facet
#' @export
vg_scale_fy <- wrapper_function(vg_scale_facet, which = "fy", drop = c("inset_left", "inset_right"))

#' Set the color scale's properties
#'
#' `vg_scale_color()` sets the properties of the color scale (`colorScale`,
#' `colorDomain`, ...), used by `fill` and `stroke` when they're mapped to
#' data. For the scale's label and tick format, see [vg_guide_color()]; to
#' add a color legend, see [vg_legend_color()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param type `<"linear" | "pow" | "sqrt" | "log" | "symlog" | "utc" | "time" | "point" | "band" | "ordinal" | ... | NULL | param()>` The *color* scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`colorScale`).
#' @param domain `<vector | "Fixed" | param()>` The extent of the scale’s inputs (abstract values). (`colorDomain`).
#' @param range `<vector | "Fixed" | param()>` The extent of the scale’s outputs (visual values). (`colorRange`).
#' @param scheme `<"Accent" | "Category10" | "Dark2" | "Observable10" | "Paired" | "Pastel1" | "Pastel2" | "Set1" | "Set2" | "Set3" | ... | param()>` If specified, shorthand for setting the **colorRange** or **colorInterpolate** option of a *color* scale. (`colorScheme`).
#' @param interpolate `<"number" | "rgb" | "hsl" | "hcl" | "lab" | param()>` How to interpolate color range values. (`colorInterpolate`).
#' @param pivot `<any | param()>` For a diverging color scale, the input value (abstract value) that divides the domain into two parts; defaults to 0 for *diverging* scales, dividing the domain into negative and positive parts; defaults to 1 for *diverging-log* scales. (`colorPivot`).
#' @param symmetric `<boolean | param()>` For a diverging color scale, if true (the default), extend the domain to ensure that the lower part of the domain (below the **pivot**) is commensurate with the upper part of the domain (above the **pivot**). (`colorSymmetric`).
#' @param nice `<boolean | number | "day"/"week"/"month"/... | param()>` If true, or a tick count or interval, extend the domain to nice round values. (`colorNice`).
#' @param zero `<boolean | param()>` Whether the **domain** must include zero. (`colorZero`).
#' @param reverse `<boolean | param()>` Whether to reverse the scale’s encoding; equivalent to reversing either the **domain** or **range**. (`colorReverse`).
#' @param clamp `<boolean | param()>` If true, values below the domain minimum are treated as the domain minimum, and values above the domain maximum are treated as the domain maximum. (`colorClamp`).
#' @param base `<number | param()>` A log scale’s base; defaults to 10. (`colorBase`).
#' @param exponent `<number | param()>` A power scale’s exponent (*e.g.*, 0.5 for sqrt); defaults to 1 for a linear scale. (`colorExponent`).
#' @param constant `<number | param()>` A symlog scale’s constant, expressing the magnitude of the linear region around the origin; defaults to 1. (`colorConstant`).
#' @param percent `<boolean | param()>` If true, shorthand for a transform suitable for percentages, mapping proportions in 0, 1 to 0, 100. (`colorPercent`).
#' @param n `<number | param()>` For a *quantile* scale, the number of quantiles (creates *n* - 1 thresholds); for a *quantize* scale, the approximate number of thresholds; defaults to 5. (`colorN`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, fill = ~g) |>
#'   vg_scale_color(scheme = "Viridis", type = "linear")
vg_scale_color <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, scheme = vg_unset, interpolate = vg_unset, pivot = vg_unset, symmetric = vg_unset, nice = vg_unset, zero = vg_unset, reverse = vg_unset, clamp = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, n = vg_unset, ...) {
  context <- "vg_scale_color()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", scheme = "Scheme", interpolate = "Interpolate", pivot = "Pivot", symmetric = "Symmetric", nice = "Nice", zero = "Zero", reverse = "Reverse", clamp = "Clamp", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent", n = "N")
  attrs <- prefixed_attrs("color", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set the radius, length, and opacity scales' properties
#'
#' `vg_scale_r()`, `vg_scale_length()`, and `vg_scale_opacity()` set the scale properties of the `r`, `length`, and `opacity` channels. They take the same arguments, except those noted below as belonging to only some of them; each is described below.
#'
#' `vg_scale_r()` (also called `vg_scale_radius()`) sets the properties of
#' the radius scale (`rScale`, `rDomain`, ...), used by a `dot` mark's `r`
#' when it's mapped to data. For the scale's label, see [vg_guide_r()]; a
#' legend for sizes can be made with [vg_legend_symbol()].
#'
#' `vg_scale_length()` sets the properties of the length scale
#' (`lengthScale`, `lengthDomain`, ...), used by a `vector` or `spike`
#' mark's `length` when it's mapped to data.
#'
#' `vg_scale_opacity()` sets the properties of the opacity scale
#' (`opacityScale`, `opacityDomain`, ...), used by `opacity`, `fill_opacity`
#' and `stroke_opacity` when they're mapped to data. For the scale's label
#' and tick format, see [vg_guide_opacity()]; to add an opacity legend, see
#' [vg_legend_opacity()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param type `<"linear" | "pow" | "sqrt" | "log" | "symlog" | "utc" | "time" | "identity" | NULL | param()>` The scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`rScale`/`lengthScale`/`opacityScale`).
#' @param domain `<vector | "Fixed" | param()>` The extent of the scale’s inputs (abstract values). (`rDomain`/`lengthDomain`/`opacityDomain`).
#' @param range `<vector | "Fixed" | param()>` The extent of the scale’s outputs (visual values). (`rRange`/`lengthRange`/`opacityRange`).
#' @param nice `<boolean | number | "day"/"week"/"month"/... | param()>` If true, or a tick count or interval, extend the domain to nice round values. (`rNice`/`lengthNice`/`opacityNice`).
#' @param zero `<boolean | param()>` Whether the **domain** must include zero. (`rZero`/`lengthZero`/`opacityZero`).
#' @param clamp `<any>` (`vg_scale_r()`, `vg_scale_length()`) or `<boolean | param()>` (`vg_scale_opacity()`) If true, values below the domain minimum are treated as the domain minimum, and values above the domain maximum are treated as the domain maximum. (`rClamp`/`lengthClamp`/`opacityClamp`).
#' @param base `<number | param()>` A log scale’s base; defaults to 10. (`rBase`/`lengthBase`/`opacityBase`).
#' @param exponent `<number | param()>` A power scale’s exponent (*e.g.*, 0.5 for sqrt); defaults to 1 for a linear scale. (`rExponent`/`lengthExponent`/`opacityExponent`).
#' @param constant `<number | param()>` A symlog scale’s constant, expressing the magnitude of the linear region around the origin; defaults to 1. (`rConstant`/`lengthConstant`/`opacityConstant`).
#' @param percent `<boolean | param()>` If true, shorthand for a transform suitable for percentages, mapping proportions in 0, 1 to 0, 100. (`rPercent`/`lengthPercent`/`opacityPercent`).
#' @param reverse `<boolean | param()>` Whether to reverse the scale’s encoding; equivalent to reversing either the **domain** or **range**. (`opacityReverse`). Only for `vg_scale_opacity()`.
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family scale functions
#' @rdname vg_scale_r
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, r = ~g) |>
#'   vg_scale_r(range = c(0, 20), zero = TRUE)
#' vg_mark_vector(x = ~a, y = ~b, length = ~g) |>
#'   vg_scale_length(range = c(0, 20))
#' vg_mark_dot(x = ~a, y = ~b, opacity = ~g) |>
#'   vg_scale_opacity(range = c(0.2, 1))
vg_scale_r <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, nice = vg_unset, zero = vg_unset, clamp = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, ...) {
  context <- "vg_scale_r()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", nice = "Nice", zero = "Zero", clamp = "Clamp", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent")
  attrs <- prefixed_attrs("r", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_scale_r
#' @export
vg_scale_radius <- vg_scale_r

#' @rdname vg_scale_r
#' @export
vg_scale_length <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, nice = vg_unset, zero = vg_unset, clamp = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, ...) {
  context <- "vg_scale_length()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", nice = "Nice", zero = "Zero", clamp = "Clamp", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent")
  attrs <- prefixed_attrs("length", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_scale_r
#' @export
vg_scale_opacity <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, nice = vg_unset, zero = vg_unset, reverse = vg_unset, clamp = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, ...) {
  context <- "vg_scale_opacity()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", nice = "Nice", zero = "Zero", reverse = "Reverse", clamp = "Clamp", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent")
  attrs <- prefixed_attrs("opacity", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set the symbol scale's properties
#'
#' `vg_scale_symbol()` sets the properties of the symbol scale
#' (`symbolScale`, `symbolDomain`, `symbolRange`), used by a `dot` mark's
#' `symbol` when it's mapped to data. To add a symbol legend, see
#' [vg_legend_symbol()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param type `<"ordinal" | "identity" | NULL | param()>` The *symbol* scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`symbolScale`).
#' @param domain `<vector | "Fixed" | param()>` The extent of the scale’s inputs (abstract values). (`symbolDomain`).
#' @param range `<vector | "Fixed" | param()>` The extent of the scale’s outputs (visual values). (`symbolRange`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, symbol = ~g) |>
#'   vg_scale_symbol(range = c("circle", "square", "triangle"))
vg_scale_symbol <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, ...) {
  context <- "vg_scale_symbol()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range")
  attrs <- prefixed_attrs("symbol", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set global default scale properties (all ordinal position scales)
#'
#' `vg_scale_all()` sets defaults for all of a plot's ordinal position scales
#' (`x`, `y`, `fx`, `fy`), used by any of them that doesn't set its own
#' value -- unlike [vg_scale_position()] and [vg_scale_facet()], which set
#' one scale. For axis defaults, see [vg_guide_all()].
#'
#' See [vg_value_types] for what the `<...>` notation below (`number`, `param()`, ...) means.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param padding `<number | param()>` For *band* scales, how much of the **range** to reserve to separate adjacent bands; defaults to 0.1 (10%). (`padding`).
#' @param align `<number | param()>` How to distribute unused space in the **range** for *point* and *band* scales. (`align`).
#' @param inset `<number | param()>` Shorthand to set the same default for all four insets: **insetTop**, **insetRight**, **insetBottom**, and **insetLeft**. (`inset`).
#' @param ... Additional plot-level attributes not covered above, e.g.
#'   `x_domain =` (Mosaic's `xDomain`, written in snake_case).
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b) |>
#'   vg_scale_all(padding = 0.2)
vg_scale_all <- function(spec = NULL, padding = vg_unset, align = vg_unset, inset = vg_unset, ...) {
  context <- "vg_scale_all()"
  suffixes <- c(padding = "padding", align = "align", inset = "inset")
  attrs <- prefixed_attrs("", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

