# Generated by data-raw/update-schema.R from mosaic's JSON schema.
# DO NOT EDIT BY HAND -- rerun that script instead.
#
# One vg_scale_*() constructor per scale channel/family in mosaic-spec's
# PlotAttributes -- see data-raw/update-schema.R's own comments for how
# properties are classified into these.

#' @include utils.R
NULL

# Which InsetLeft/InsetRight vs InsetTop/InsetBottom pair applies to which
# `which` value -- used by add_inset_attrs() (R/utils.R).
vg_inset_side_suffixes <- list(
  x = c(inset_left = "InsetLeft", inset_right = "InsetRight"),
  y = c(inset_top = "InsetTop", inset_bottom = "InsetBottom"),
  fx = c(inset_left = "InsetLeft", inset_right = "InsetRight"),
  fy = c(inset_top = "InsetTop", inset_bottom = "InsetBottom")
)

vg_position_counterpart <- c(x = "y", y = "x", fx = "fy", fy = "fx")

#' Set position scale properties (x or y)
#'
#' `vg_scale_x()`/`vg_scale_y()` set the scale properties mosaic-spec
#' exposes per positional axis (`xScale`, `xDomain`, ... -- substitute
#' `y` for the vertical axis). These are already plot-level attributes
#' that [vg_plot()]/[vg_attributes()] accept directly by their raw
#' camelCase names; this is a discoverable, snake_case-argument
#' convenience layer on top of that. `vg_scale_x()` and `vg_scale_y()`
#' are thin wrappers around the generic `vg_scale_position()`.
#'
#' Like [vg_plot()], this can be piped in alongside marks/interactors --
#' it only ever sets attributes on the current plot fragment, so it
#' never needs to come last in a chain. For the analogous facet scales
#' (`fx`/`fy`), see [vg_scale_facet()].
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param which Which position scale this sets: `"x"` or `"y"`.
#' @param type The *x* scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`xScale`/`yScale`).
#' @param domain The extent of the scale’s inputs (abstract values). (`xDomain`/`yDomain`).
#' @param range The extent of the scale’s outputs (visual values). (`xRange`/`yRange`).
#' @param nice If true, or a tick count or interval, extend the domain to nice round values. (`xNice`/`yNice`).
#' @param zero Whether the **domain** must include zero. (`xZero`/`yZero`).
#' @param reverse Whether to reverse the scale’s encoding; equivalent to reversing either the **domain** or **range**. (`xReverse`/`yReverse`).
#' @param clamp If true, values below the domain minimum are treated as the domain minimum, and values above the domain maximum are treated as the domain maximum. (`xClamp`/`yClamp`).
#' @param round If true, round the output value to the nearest integer (pixel); useful for crisp edges when rendering. (`xRound`/`yRound`).
#' @param padding For *band* scales, how much of the **range** to reserve to separate adjacent bands; defaults to 0.1 (10%). (`xPadding`/`yPadding`).
#' @param padding_inner For a *band* scale, how much of the range to reserve to separate adjacent bands. (`xPaddingInner`/`yPaddingInner`).
#' @param padding_outer For a *band* scale, how much of the range to reserve to inset first and last bands. (`xPaddingOuter`/`yPaddingOuter`).
#' @param align How to distribute unused space in the **range** for *point* and *band* scales. (`xAlign`/`yAlign`).
#' @param inset Shorthand to set the same default for all four insets: **insetTop**, **insetRight**, **insetBottom**, and **insetLeft**. (`xInset`/`yInset`).
#' @param base A log scale’s base; defaults to 10. (`xBase`/`yBase`).
#' @param exponent A power scale’s exponent (*e.g.*, 0.5 for sqrt); defaults to 1 for a linear scale. (`xExponent`/`yExponent`).
#' @param constant A symlog scale’s constant, expressing the magnitude of the linear region around the origin; defaults to 1. (`xConstant`/`yConstant`).
#' @param percent If true, shorthand for a transform suitable for percentages, mapping proportions in 0, 1 to 0, 100. (`xPercent`/`yPercent`).
#' @param inset_left,inset_right Pixel inset at the left/right end of the range; only meaningful for `which = "x"` (`xInsetLeft`/`xInsetRight`).
#' @param inset_top,inset_bottom Pixel inset at the top/bottom end of the range; only meaningful for `which = "y"` (`yInsetTop`/`yInsetBottom`).
#' @param ... Additional plot-level attributes not covered above, by their
#'   raw mosaic-spec camelCase name.
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b) |>
#'   vg_scale_x(type = "log") |>
#'   vg_scale_y(zero = TRUE, nice = TRUE)
vg_scale_position <- function(spec = NULL, which = c("x", "y"), type = vg_unset, domain = vg_unset, range = vg_unset, nice = vg_unset, zero = vg_unset, reverse = vg_unset, clamp = vg_unset, round = vg_unset, padding = vg_unset, padding_inner = vg_unset, padding_outer = vg_unset, align = vg_unset, inset = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, inset_left = vg_unset, inset_right = vg_unset, inset_top = vg_unset, inset_bottom = vg_unset, ...) {
  which <- match.arg(which)
  context <- paste0("vg_scale_", which, "()")
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", nice = "Nice", zero = "Zero", reverse = "Reverse", clamp = "Clamp", round = "Round", padding = "Padding", padding_inner = "PaddingInner", padding_outer = "PaddingOuter", align = "Align", inset = "Inset", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent")
  attrs <- prefixed_attrs(which, suffixes, environment())
  attrs <- add_inset_attrs(attrs, which, environment(), context)
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_scale_position
#' @export
vg_scale_x <- wrapper_function(vg_scale_position, which = "x", drop = c("inset_top", "inset_bottom"))

#' @rdname vg_scale_position
#' @export
vg_scale_y <- wrapper_function(vg_scale_position, which = "y", drop = c("inset_left", "inset_right"))

#' Set facet scale properties (fx or fy)
#'
#' `vg_scale_fx()`/`vg_scale_fy()` set the scale properties mosaic-spec
#' exposes per facet axis (`fxDomain`, `fxPadding`, ... -- substitute
#' `fy` for the row facet axis). Facet scales are always band scales,
#' so this covers fewer properties than [vg_scale_position()] (no
#' `type`, `nice`, `zero`, `clamp`, or the log/pow/symlog-only
#' properties) -- exactly which ones is derived from the schema, not
#' hand-picked. `vg_scale_fx()` and `vg_scale_fy()` are thin wrappers
#' around the generic `vg_scale_facet()`.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param which Which facet scale this sets: `"fx"` or `"fy"`.
#' @param domain The extent of the scale’s inputs (abstract values). (`fxDomain`/`fyDomain`).
#' @param range The extent of the scale’s outputs (visual values). (`fxRange`/`fyRange`).
#' @param reverse Whether to reverse the scale’s encoding; equivalent to reversing either the **domain** or **range**. (`fxReverse`/`fyReverse`).
#' @param round If true, round the output value to the nearest integer (pixel); useful for crisp edges when rendering. (`fxRound`/`fyRound`).
#' @param padding For *band* scales, how much of the **range** to reserve to separate adjacent bands; defaults to 0.1 (10%). (`fxPadding`/`fyPadding`).
#' @param padding_inner For a *band* scale, how much of the range to reserve to separate adjacent bands. (`fxPaddingInner`/`fyPaddingInner`).
#' @param padding_outer For a *band* scale, how much of the range to reserve to inset first and last bands. (`fxPaddingOuter`/`fyPaddingOuter`).
#' @param align How to distribute unused space in the **range** for *point* and *band* scales. (`fxAlign`/`fyAlign`).
#' @param inset Shorthand to set the same default for all four insets: **insetTop**, **insetRight**, **insetBottom**, and **insetLeft**. (`fxInset`/`fyInset`).
#' @param inset_left,inset_right Pixel inset at the left/right end of the range; only meaningful for `which = "fx"` (`fxInsetLeft`/`fxInsetRight`).
#' @param inset_top,inset_bottom Pixel inset at the top/bottom end of the range; only meaningful for `which = "fy"` (`fyInsetTop`/`fyInsetBottom`).
#' @param ... Additional plot-level attributes not covered above, by their
#'   raw mosaic-spec camelCase name.
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, fx = ~g) |>
#'   vg_scale_fx(padding = 0.1)
vg_scale_facet <- function(spec = NULL, which = c("fx", "fy"), domain = vg_unset, range = vg_unset, reverse = vg_unset, round = vg_unset, padding = vg_unset, padding_inner = vg_unset, padding_outer = vg_unset, align = vg_unset, inset = vg_unset, inset_left = vg_unset, inset_right = vg_unset, inset_top = vg_unset, inset_bottom = vg_unset, ...) {
  which <- match.arg(which)
  context <- paste0("vg_scale_", which, "()")
  suffixes <- c(domain = "Domain", range = "Range", reverse = "Reverse", round = "Round", padding = "Padding", padding_inner = "PaddingInner", padding_outer = "PaddingOuter", align = "Align", inset = "Inset")
  attrs <- prefixed_attrs(which, suffixes, environment())
  attrs <- add_inset_attrs(attrs, which, environment(), context)
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_scale_facet
#' @export
vg_scale_fx <- wrapper_function(vg_scale_facet, which = "fx", drop = c("inset_top", "inset_bottom"))

#' @rdname vg_scale_facet
#' @export
vg_scale_fy <- wrapper_function(vg_scale_facet, which = "fy", drop = c("inset_left", "inset_right"))

#' Set the color scale's properties
#'
#' `vg_scale_color()` sets the scale properties mosaic-spec exposes for
#' the `color` channel (`colorScale`, `colorDomain`, ... -- the scale
#' that `fill`/`stroke` encodings are bound to unless they're a literal
#' constant). Unlike `vg_scale_x()`/`vg_scale_y()`, there's only one
#' color channel, so `vg_scale_color()` isn't built from a `which =`
#' generic -- it's the whole implementation. For the axis-guide
#' properties (`colorLabel`/`colorTickFormat`), see [vg_guide_color()];
#' for an actual rendered color legend, see [vg_legend_color()] -- a
#' different (if related) thing, a standalone/embedded legend mark
#' rather than a plot attribute.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param type The *color* scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`colorScale`).
#' @param domain The extent of the scale’s inputs (abstract values). (`colorDomain`).
#' @param range The extent of the scale’s outputs (visual values). (`colorRange`).
#' @param scheme If specified, shorthand for setting the **colorRange** or **colorInterpolate** option of a *color* scale. (`colorScheme`).
#' @param interpolate How to interpolate color range values. (`colorInterpolate`).
#' @param pivot For a diverging color scale, the input value (abstract value) that divides the domain into two parts; defaults to 0 for *diverging* scales, dividing the domain into negative and positive parts; defaults to 1 for *diverging-log* scales. (`colorPivot`).
#' @param symmetric For a diverging color scale, if true (the default), extend the domain to ensure that the lower part of the domain (below the **pivot**) is commensurate with the upper part of the domain (above the **pivot**). (`colorSymmetric`).
#' @param nice If true, or a tick count or interval, extend the domain to nice round values. (`colorNice`).
#' @param zero Whether the **domain** must include zero. (`colorZero`).
#' @param reverse Whether to reverse the scale’s encoding; equivalent to reversing either the **domain** or **range**. (`colorReverse`).
#' @param clamp If true, values below the domain minimum are treated as the domain minimum, and values above the domain maximum are treated as the domain maximum. (`colorClamp`).
#' @param base A log scale’s base; defaults to 10. (`colorBase`).
#' @param exponent A power scale’s exponent (*e.g.*, 0.5 for sqrt); defaults to 1 for a linear scale. (`colorExponent`).
#' @param constant A symlog scale’s constant, expressing the magnitude of the linear region around the origin; defaults to 1. (`colorConstant`).
#' @param percent If true, shorthand for a transform suitable for percentages, mapping proportions in 0, 1 to 0, 100. (`colorPercent`).
#' @param n For a *quantile* scale, the number of quantiles (creates *n* - 1 thresholds); for a *quantize* scale, the approximate number of thresholds; defaults to 5. (`colorN`).
#' @param ... Additional plot-level attributes not covered above, by their
#'   raw mosaic-spec camelCase name.
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, fill = ~g) |>
#'   vg_scale_color(scheme = "Viridis", type = "linear")
vg_scale_color <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, scheme = vg_unset, interpolate = vg_unset, pivot = vg_unset, symmetric = vg_unset, nice = vg_unset, zero = vg_unset, reverse = vg_unset, clamp = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, n = vg_unset, ...) {
  context <- "vg_scale_color()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", scheme = "Scheme", interpolate = "Interpolate", pivot = "Pivot", symmetric = "Symmetric", nice = "Nice", zero = "Zero", reverse = "Reverse", clamp = "Clamp", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent", n = "N")
  attrs <- prefixed_attrs("color", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set the opacity scale's properties
#'
#' `vg_scale_opacity()` sets the scale properties mosaic-spec exposes
#' for the `opacity` channel (`opacityScale`, `opacityDomain`, ... --
#' the scale that `opacity`/`fillOpacity`/`strokeOpacity` encodings are
#' bound to unless they're a literal constant). For the axis-guide
#' properties, see [vg_guide_opacity()]; for an actual rendered opacity
#' legend, see [vg_legend_opacity()].
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param type The *opacity* scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`opacityScale`).
#' @param domain The extent of the scale’s inputs (abstract values). (`opacityDomain`).
#' @param range The extent of the scale’s outputs (visual values). (`opacityRange`).
#' @param nice If true, or a tick count or interval, extend the domain to nice round values. (`opacityNice`).
#' @param zero Whether the **domain** must include zero. (`opacityZero`).
#' @param reverse Whether to reverse the scale’s encoding; equivalent to reversing either the **domain** or **range**. (`opacityReverse`).
#' @param clamp If true, values below the domain minimum are treated as the domain minimum, and values above the domain maximum are treated as the domain maximum. (`opacityClamp`).
#' @param base A log scale’s base; defaults to 10. (`opacityBase`).
#' @param exponent A power scale’s exponent (*e.g.*, 0.5 for sqrt); defaults to 1 for a linear scale. (`opacityExponent`).
#' @param constant A symlog scale’s constant, expressing the magnitude of the linear region around the origin; defaults to 1. (`opacityConstant`).
#' @param percent If true, shorthand for a transform suitable for percentages, mapping proportions in 0, 1 to 0, 100. (`opacityPercent`).
#' @param ... Additional plot-level attributes not covered above, by their
#'   raw mosaic-spec camelCase name.
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, opacity = ~g) |>
#'   vg_scale_opacity(range = c(0.2, 1))
vg_scale_opacity <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, nice = vg_unset, zero = vg_unset, reverse = vg_unset, clamp = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, ...) {
  context <- "vg_scale_opacity()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", nice = "Nice", zero = "Zero", reverse = "Reverse", clamp = "Clamp", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent")
  attrs <- prefixed_attrs("opacity", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set the radius scale's properties
#'
#' `vg_scale_r()` (aliased as `vg_scale_radius()`) sets the scale
#' properties mosaic-spec exposes for the `r` channel (`rScale`,
#' `rDomain`, ... -- the scale that a `dot`/`circle` mark's `r`
#' encoding is bound to unless it's a literal constant). Which
#' properties exist here (e.g. no `reverse` -- mosaic doesn't define
#' `rReverse`) is derived from the schema, not hand-picked. For the
#' axis-guide property, see [vg_guide_r()]/[vg_guide_radius()]; for an
#' actual rendered radius/size legend, see [vg_legend_symbol()]
#' (mosaic doesn't have a dedicated `r`-typed legend).
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param type The *r* (radius) scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`rScale`).
#' @param domain The extent of the scale’s inputs (abstract values). (`rDomain`).
#' @param range The extent of the scale’s outputs (visual values). (`rRange`).
#' @param nice If true, or a tick count or interval, extend the domain to nice round values. (`rNice`).
#' @param zero Whether the **domain** must include zero. (`rZero`).
#' @param clamp If true, values below the domain minimum are treated as the domain minimum, and values above the domain maximum are treated as the domain maximum. (`rClamp`).
#' @param base A log scale’s base; defaults to 10. (`rBase`).
#' @param exponent A power scale’s exponent (*e.g.*, 0.5 for sqrt); defaults to 1 for a linear scale. (`rExponent`).
#' @param constant A symlog scale’s constant, expressing the magnitude of the linear region around the origin; defaults to 1. (`rConstant`).
#' @param percent If true, shorthand for a transform suitable for percentages, mapping proportions in 0, 1 to 0, 100. (`rPercent`).
#' @param ... Additional plot-level attributes not covered above, by their
#'   raw mosaic-spec camelCase name.
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, r = ~g) |>
#'   vg_scale_r(range = c(0, 20), zero = TRUE)
vg_scale_r <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, nice = vg_unset, zero = vg_unset, clamp = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, ...) {
  context <- "vg_scale_r()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", nice = "Nice", zero = "Zero", clamp = "Clamp", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent")
  attrs <- prefixed_attrs("r", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' @rdname vg_scale_r
#' @export
vg_scale_radius <- vg_scale_r

#' Set the length scale's properties
#'
#' `vg_scale_length()` sets the scale properties mosaic-spec exposes
#' for the `length` channel (`lengthScale`, `lengthDomain`, ... -- the
#' scale that a `vector`/`spike` mark's `length` encoding is bound to
#' unless it's a literal constant). Mosaic doesn't define a length
#' axis-guide or legend, so there's no `vg_guide_length()`/
#' `vg_legend_length()` to pair with this.
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param type The *length* scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`lengthScale`).
#' @param domain The extent of the scale’s inputs (abstract values). (`lengthDomain`).
#' @param range The extent of the scale’s outputs (visual values). (`lengthRange`).
#' @param nice If true, or a tick count or interval, extend the domain to nice round values. (`lengthNice`).
#' @param zero Whether the **domain** must include zero. (`lengthZero`).
#' @param clamp If true, values below the domain minimum are treated as the domain minimum, and values above the domain maximum are treated as the domain maximum. (`lengthClamp`).
#' @param base A log scale’s base; defaults to 10. (`lengthBase`).
#' @param exponent A power scale’s exponent (*e.g.*, 0.5 for sqrt); defaults to 1 for a linear scale. (`lengthExponent`).
#' @param constant A symlog scale’s constant, expressing the magnitude of the linear region around the origin; defaults to 1. (`lengthConstant`).
#' @param percent If true, shorthand for a transform suitable for percentages, mapping proportions in 0, 1 to 0, 100. (`lengthPercent`).
#' @param ... Additional plot-level attributes not covered above, by their
#'   raw mosaic-spec camelCase name.
#' @family scale functions
#' @export
#' @examples
#' vg_mark_vector(x = ~a, y = ~b, length = ~g) |>
#'   vg_scale_length(range = c(0, 20))
vg_scale_length <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, nice = vg_unset, zero = vg_unset, clamp = vg_unset, base = vg_unset, exponent = vg_unset, constant = vg_unset, percent = vg_unset, ...) {
  context <- "vg_scale_length()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range", nice = "Nice", zero = "Zero", clamp = "Clamp", base = "Base", exponent = "Exponent", constant = "Constant", percent = "Percent")
  attrs <- prefixed_attrs("length", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set the symbol scale's properties
#'
#' `vg_scale_symbol()` sets the scale properties mosaic-spec exposes
#' for the `symbol` channel (`symbolScale`, `symbolDomain`,
#' `symbolRange` -- the scale that a `dot`'s `symbol` encoding is bound
#' to unless it's a literal constant). Mosaic doesn't define a symbol
#' axis-guide, but does have a dedicated legend type -- see
#' [vg_legend_symbol()].
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param type The *symbol* scale type, affecting how the scale encodes abstract data, say by applying a mathematical transformation. (`symbolScale`).
#' @param domain The extent of the scale’s inputs (abstract values). (`symbolDomain`).
#' @param range The extent of the scale’s outputs (visual values). (`symbolRange`).
#' @param ... Additional plot-level attributes not covered above, by their
#'   raw mosaic-spec camelCase name.
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b, symbol = ~g) |>
#'   vg_scale_symbol(range = c("circle", "square", "triangle"))
vg_scale_symbol <- function(spec = NULL, type = vg_unset, domain = vg_unset, range = vg_unset, ...) {
  context <- "vg_scale_symbol()"
  suffixes <- c(type = "Scale", domain = "Domain", range = "Range")
  attrs <- prefixed_attrs("symbol", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

#' Set global default scale properties (all ordinal position scales)
#'
#' `vg_scale_all()` sets mosaic-spec's plot-wide fallback defaults --
#' unlike `xAlign`/`xPadding`/etc. (set via [vg_scale_position()]) or
#' `fxAlign`/etc. (via [vg_scale_facet()]), which only affect one scale,
#' these bare attributes are mosaic's own defaults applied to *every*
#' ordinal position scale (`x`, `y`, `fx`, `fy`) that doesn't set its
#' own value. For the analogous axis-guide defaults, see
#' [vg_guide_all()].
#'
#' @param spec A plot fragment or `vgspec` to set this scale on, or `NULL` to
#'   start a new plot fragment with just these attributes.
#' @param padding For *band* scales, how much of the **range** to reserve to separate adjacent bands; defaults to 0.1 (10%). (`padding`).
#' @param align How to distribute unused space in the **range** for *point* and *band* scales. (`align`).
#' @param inset Shorthand to set the same default for all four insets: **insetTop**, **insetRight**, **insetBottom**, and **insetLeft**. (`inset`).
#' @param ... Additional plot-level attributes not covered above, by their
#'   raw mosaic-spec camelCase name.
#' @family scale functions
#' @export
#' @examples
#' vg_mark_dot(x = ~a, y = ~b) |>
#'   vg_scale_all(padding = 0.2)
vg_scale_all <- function(spec = NULL, padding = vg_unset, align = vg_unset, inset = vg_unset, ...) {
  context <- "vg_scale_all()"
  suffixes <- c(padding = "padding", align = "align", inset = "inset")
  attrs <- prefixed_attrs("", suffixes, environment())
  apply_plot_attrs(spec, attrs, list(...), context)
}

